import type { JobPosting } from "@/lib/jobs/types";
import { calculateJobMatch, type JobMatchProfile } from "@/lib/jobs/jobMatching";
import { recommendForMissingSkills } from "@/lib/learning/recommendStudyResources";

const date = (value: string | null) => value ? new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(value)) : null;
export default function JobCard({ job, profile }: { job: JobPosting; profile?: JobMatchProfile | null }) {
  const match = profile ? calculateJobMatch(job, profile) : null;
  const learning = match ? recommendForMissingSkills(match.missingSkills, 2) : [];
  return <article className="border-t border-slate-200 py-6 first:border-t-0">
    <div className="grid gap-5 sm:grid-cols-[1fr_auto]"><div className="min-w-0"><div className="flex flex-wrap items-baseline gap-x-3 gap-y-1"><h3 className="text-xl font-bold text-slate-950">{job.title}</h3>{match?.score !== null && match && <span className="text-sm font-bold text-blue-700">{match.score}% match</span>}</div><p className="mt-1 font-semibold text-slate-700">{job.company ?? "Employer not supplied"}</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-sm text-slate-500"><span>{job.locationText ?? job.countryName ?? "Location not supplied"}</span>{job.workplaceType && <span className="capitalize">{job.workplaceType}</span>}{job.employmentType && <span>{job.employmentType}</span>}{date(job.publishedAt) && <span>Posted {date(job.publishedAt)}</span>}</div></div><a href={job.applyUrl} target="_blank" rel="noopener noreferrer" className="product-button product-button-primary self-start">{job.providerMetadata.directApplication ? "Apply on source" : "View source"}</a></div>
    {match && <div className="mt-4 grid gap-2 text-sm sm:grid-cols-2"><p><span className="font-semibold text-slate-700">Matched:</span> <span className="text-slate-600">{match.matchedSkills.slice(0,3).join(", ") || "Career and preferences"}</span></p><p><span className="font-semibold text-slate-700">Top gap:</span> <span className="text-slate-600">{match.missingSkills[0] ?? match.negativeFactors[0] ?? "No mapped gap"}</span></p></div>}
    {!profile && <p className="mt-4 text-sm text-slate-500">Complete your profile to calculate a personalized match.</p>}
    <details className="mt-4 text-sm"><summary className="cursor-pointer font-semibold text-blue-700">Why this matches</summary><div className="mt-3 max-w-3xl space-y-2 border-l-2 border-slate-200 pl-4 text-slate-600">{job.description && <p className="line-clamp-3 leading-6">{job.description}</p>}{job.skills.length > 0 && <p><strong>Role skills:</strong> {job.skills.slice(0,6).join(", ")}</p>}{match && <p className="capitalize">{match.confidence} confidence · {match.evidenceCoverage}% evidence coverage</p>}{learning.map(({resource,matchedSkills}) => <a key={resource.id} href={resource.url} target="_blank" rel="noopener noreferrer" className="block font-semibold text-blue-700">Learn {matchedSkills.join(", ")} with {resource.provider} →</a>)}</div></details><p className="mt-4 text-xs text-slate-500">Source: {job.sourceName}</p>
  </article>;
}
