"use client";
import { FormEvent, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import JobCard from "./JobCard";
import type { JobPosting, JobSearchResponse } from "@/lib/jobs/types";
import type { JobMatchProfile } from "@/lib/jobs/jobMatching";
import { supabase } from "@/lib/supabase";

export default function JobsSearchClient() {
  const initial = useSearchParams();
  const [q, setQ] = useState(initial.get("q") ?? ""); const [country, setCountry] = useState(initial.get("country") ?? "sweden");
  const [location, setLocation] = useState(initial.get("location") ?? ""); const [workplace, setWorkplace] = useState(initial.get("workplaceType") ?? ""); const [sort, setSort] = useState(initial.get("sort") ?? "relevance");
  const [jobs, setJobs] = useState<JobPosting[]>([]); const [page, setPage] = useState(1); const [state, setState] = useState<"loading" | "ready" | "error">("loading"); const [meta, setMeta] = useState<JobSearchResponse | null>(null); const [error, setError] = useState("");
  const [profile, setProfile] = useState<JobMatchProfile | null>(null);
  async function load(nextPage = 1, append = false) { setState("loading"); setError(""); const params = new URLSearchParams({ q, country, location, workplaceType: workplace, sort, page: String(nextPage), limit: "12" }); const career = initial.get("career"); if (career) params.set("career", career);
    try { const response = await fetch(`/api/jobs/search?${params}`); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Job search failed"); setMeta(data); setJobs((current) => append ? [...current, ...data.results] : data.results); setPage(nextPage); setState("ready"); } catch (e) { setError(e instanceof Error ? e.message : "Job search failed"); setState("error"); }
  }
  // Initial query is intentionally fetched once; later searches use the form.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { void load(); void supabase.auth.getUser().then(async ({ data }) => { if (!data.user) return; const result = await supabase.from("user_career_profiles").select("current_career,current_country,skills,remote_preference").eq("user_id", data.user.id).maybeSingle(); if (result.data) setProfile({ careerSlug: result.data.current_career, countryCode: result.data.current_country === "sweden" ? "SE" : null, skills: result.data.skills ?? [], workplaceType: result.data.remote_preference === "required" ? "remote" : null }); }); }, []);
  function submit(event: FormEvent) { event.preventDefault(); void load(1); }
  return <div><form onSubmit={submit} className="grid gap-3 rounded-3xl border border-white/10 bg-white/[0.035] p-5 md:grid-cols-2 lg:grid-cols-6"><label className="lg:col-span-2"><span className="sr-only">Job title or skill</span><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Job title or skill" maxLength={120} className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:border-blue-300" /></label><label><span className="sr-only">Country</span><select value={country} onChange={(e) => setCountry(e.target.value)} className="w-full rounded-xl border border-white/10 bg-[#0b1527] px-4 py-3"><option value="sweden">Sweden</option><option value="germany">Germany</option><option value="france">France</option><option value="netherlands">Netherlands</option><option value="denmark">Denmark</option><option value="finland">Finland</option><option value="norway">Norway</option><option value="canada">Canada</option><option value="india">India</option></select></label><label><span className="sr-only">Location</span><input value={location} onChange={(e) => setLocation(e.target.value)} placeholder="City or region" maxLength={100} className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3" /></label><label><span className="sr-only">Workplace type</span><select value={workplace} onChange={(e) => setWorkplace(e.target.value)} className="w-full rounded-xl border border-white/10 bg-[#0b1527] px-4 py-3"><option value="">Any workplace</option><option value="remote">Remote</option><option value="hybrid">Hybrid</option><option value="on-site">On-site</option></select></label><button className="rounded-xl bg-blue-400 px-5 py-3 font-black text-slate-950">Search jobs</button><label><span className="sr-only">Sort order</span><select value={sort} onChange={(e) => setSort(e.target.value)} className="w-full rounded-xl border border-white/10 bg-[#0b1527] px-4 py-3"><option value="relevance">Relevance</option><option value="newest">Newest</option></select></label></form>
    {state === "loading" && !jobs.length && <div className="mt-8 rounded-2xl border border-white/10 p-8 text-slate-400">Finding current openings…</div>}{state === "error" && <div className="mt-8 rounded-2xl border border-red-300/20 bg-red-300/10 p-6 text-red-200">{error}</div>}
    {state === "ready" && meta && !meta.coverageAvailable && <div className="mt-8 rounded-3xl border border-white/10 bg-white/[0.025] p-8"><h2 className="text-2xl font-black">Live job coverage coming soon</h2><p className="mt-3 text-slate-400">SEKUR does not yet have a trustworthy live provider for this country. No substitute or fake listings are shown.</p></div>}
    {state === "ready" && meta?.coverageAvailable && !jobs.length && <div className="mt-8 rounded-2xl border border-white/10 p-8"><h2 className="text-xl font-black">No matching live jobs</h2><p className="mt-2 text-slate-400">Try broader search terms or remove a filter.</p></div>}
    {jobs.length > 0 && <><div className="mt-8 flex items-center justify-between"><p className="text-sm text-slate-400">Live results from {meta?.providersUsed.join(", ")}</p><p className="text-xs text-slate-500">Fetched {meta ? new Date(meta.fetchedAt).toLocaleTimeString() : ""}</p></div><div className="mt-4 grid gap-5 lg:grid-cols-2">{jobs.map((job) => <JobCard key={job.id} job={job} profile={profile} />)}</div>{meta?.hasMore && <button onClick={() => void load(page + 1, true)} disabled={state === "loading"} className="mx-auto mt-8 block rounded-xl border border-white/15 px-6 py-3 font-bold disabled:opacity-50">{state === "loading" ? "Loading…" : "Load more"}</button>}</>}
    {meta?.providerErrors.map((item) => <p key={item.provider} className="mt-4 text-sm text-amber-300">{item.provider} is temporarily unavailable.</p>)}
  </div>;
}
