"use client";
import { FormEvent, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import JobCard from "./JobCard";
import type { JobPosting, JobSearchResponse } from "@/lib/jobs/types";
import type { JobMatchProfile } from "@/lib/jobs/jobMatching";
import { supabase } from "@/lib/supabase";
import { resolveEntitlements } from "@/lib/personalization/entitlements";

export default function JobsSearchClient() {
  const initial=useSearchParams(); const [q,setQ]=useState(initial.get("q")??""); const [country,setCountry]=useState(initial.get("country")??"sweden"); const [location,setLocation]=useState(initial.get("location")??""); const [workplace,setWorkplace]=useState(initial.get("workplaceType")??""); const [sort,setSort]=useState(initial.get("sort")??"relevance");
  const [jobs,setJobs]=useState<JobPosting[]>([]); const [page,setPage]=useState(1); const [state,setState]=useState<"loading"|"ready"|"error">("loading"); const [meta,setMeta]=useState<JobSearchResponse|null>(null); const [error,setError]=useState(""); const [profile,setProfile]=useState<JobMatchProfile|null>(null); const [personalizedMatchLocked,setPersonalizedMatchLocked]=useState(false);
  async function load(nextPage=1,append=false){setState("loading");setError("");const params=new URLSearchParams({q,country,location,workplaceType:workplace,sort,page:String(nextPage),limit:"12"});const career=initial.get("career");if(career)params.set("career",career);try{const response=await fetch(`/api/jobs/search?${params}`);const data=await response.json();if(!response.ok)throw new Error(data.error??"Job search failed");setMeta(data);setJobs(current=>append?[...current,...data.results]:data.results);setPage(nextPage);setState("ready")}catch(e){setError(e instanceof Error?e.message:"Job search failed");setState("error")}}
  // Initial query is intentionally fetched once; later searches use the form.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(()=>{void load();void supabase.auth.getUser().then(async({data})=>{if(!data.user)return;const [profileResult,entitlementResult]=await Promise.all([supabase.from("user_career_profiles").select("current_career,current_country,skills,remote_preference,years_experience,education_level,languages").eq("user_id",data.user.id).maybeSingle(),supabase.from("user_entitlements").select("plan_key,feature_overrides,valid_until").eq("user_id",data.user.id).maybeSingle()]);const entitlement=entitlementResult.data;const expired=entitlement?.valid_until&&new Date(entitlement.valid_until).getTime()<Date.now();const allowed=!entitlementResult.error&&!expired&&resolveEntitlements(entitlement?.plan_key,entitlement?.feature_overrides??{}).personalizedJobMatch;if(!allowed){setPersonalizedMatchLocked(true);return}if(profileResult.data)setProfile({careerSlug:profileResult.data.current_career,countryCode:profileResult.data.current_country==="sweden"?"SE":null,skills:profileResult.data.skills??[],workplaceType:profileResult.data.remote_preference==="required"?"remote":null,yearsExperience:profileResult.data.years_experience,educationLevel:profileResult.data.education_level,languages:profileResult.data.languages??[]})})},[]);
  function submit(event:FormEvent){event.preventDefault();void load(1)}
  const control="w-full rounded-lg border border-slate-300 bg-white px-4 py-3 text-slate-950";
  return <div><form onSubmit={submit} className="grid gap-3 border-y border-slate-200 bg-white py-5 md:grid-cols-2 lg:grid-cols-6"><label className="lg:col-span-2"><span className="sr-only">Job title or skill</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Job title or skill" maxLength={120} className={control}/></label><label><span className="sr-only">Country</span><select value={country} onChange={e=>setCountry(e.target.value)} className={control}>{["sweden","germany","france","netherlands","denmark","finland","norway","canada","india"].map(value=><option key={value} value={value}>{value[0].toUpperCase()+value.slice(1)}</option>)}</select></label><label><span className="sr-only">Location</span><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="City or region" maxLength={100} className={control}/></label><label><span className="sr-only">Workplace type</span><select value={workplace} onChange={e=>setWorkplace(e.target.value)} className={control}><option value="">Any workplace</option><option value="remote">Remote</option><option value="hybrid">Hybrid</option><option value="on-site">On-site</option></select></label><button className="product-button product-button-primary">Search jobs</button><label><span className="sr-only">Sort order</span><select value={sort} onChange={e=>setSort(e.target.value)} className={control}><option value="relevance">Relevance</option><option value="newest">Newest</option></select></label></form>
    {personalizedMatchLocked&&<div className="mt-6 border-l-2 border-amber-500 bg-amber-50 p-4 text-sm text-amber-900">Personalized job matching requires SEKUR Pro. Job browsing and source links remain available.</div>}{state==="loading"&&!jobs.length&&<div className="mt-8 border-y border-slate-200 p-8 text-slate-500">Finding current openings…</div>}{state==="error"&&<div className="mt-8 border-l-2 border-red-500 bg-red-50 p-5 text-red-800">{error}</div>}
    {state==="ready"&&meta&&!meta.coverageAvailable&&<div className="mt-8 border-y border-slate-200 py-10"><h2 className="text-2xl font-bold">Live job coverage coming soon</h2><p className="mt-3 text-slate-600">SEKUR does not yet have a trustworthy live provider for this country. No substitute or fake listings are shown.</p></div>}
    {state==="ready"&&meta?.coverageAvailable&&!jobs.length&&<div className="mt-8 border-y border-slate-200 py-10"><h2 className="text-xl font-bold">No matching live jobs</h2><p className="mt-2 text-slate-600">Try broader search terms or remove a filter.</p></div>}
    {jobs.length>0&&<><div className="mt-8 flex items-center justify-between gap-3"><p className="text-sm text-slate-500">Live results from {meta?.providersUsed.join(", ")}</p><p className="text-xs text-slate-500">Fetched {meta?new Date(meta.fetchedAt).toLocaleTimeString():""}</p></div><div className="mt-2 divide-y divide-slate-200">{jobs.map(job=><JobCard key={job.id} job={job} profile={profile}/>)}</div>{meta?.hasMore&&<button onClick={()=>void load(page+1,true)} disabled={state==="loading"} className="product-button product-button-secondary mx-auto mt-8 flex">{state==="loading"?"Loading…":"Load more"}</button>}</>}
    {meta?.providerErrors.map(item=><p key={item.provider} className="mt-4 text-sm text-amber-700">{item.provider} is temporarily unavailable.</p>)}
  </div>;
}
