"use client";
import CountryFlag from "@/components/CountryFlag";
import ComparisonMetric from "@/components/ComparisonMetric";
import { useRouter } from "next/navigation";
import SaveComparisonControl from "@/components/user/SaveComparisonControl";
import { compareScoreRecords } from "@/lib/scoring/comparison";

type Factor={key:string;label:string;score:number;weight:number;sourceType:"official"|"market"|"community"|"research"|"estimated";explanation?:string};
type IntelligenceResult={score:number;label:"Excellent"|"Strong"|"Good"|"Moderate"|"Weak";confidence:"High"|"Medium"|"Low";factors:Factor[]};
type CompareCountry={slug:string;name:string;code:string;region:string;result:IntelligenceResult};
const description=(score:number)=>score>=90?"Excellent":score>=80?"Strong":score>=70?"Good":score>=60?"Moderate":"Weak";

export default function CompareClient({countries,initialLeft,initialRight}:{countries:CompareCountry[];initialLeft:string;initialRight:string}){
  const router=useRouter();const left=countries.find(c=>c.slug===initialLeft)??countries[0];const right=countries.find(c=>c.slug===initialRight)??countries.find(c=>c.slug!==left.slug)!;const get=(country:CompareCountry,key:string)=>country.result.factors.find(f=>f.key===key);
  function changeComparison(newLeft:string,newRight:string){if(newLeft===newRight)return;router.push(`/compare?left=${newLeft}&right=${newRight}`);router.refresh()}
  const metrics=[{key:"salary",label:"Salary"},{key:"hiring",label:"Demand"},{key:"safety",label:"Safety"},{key:"healthcare",label:"Healthcare"},{key:"visa",label:"Relocation"},{key:"work_life",label:"Work-life balance"},{key:"cost_of_living",label:"Cost efficiency"}];
  const outcomes=compareScoreRecords(metrics.map(m=>({key:m.key,label:m.label,score:get(left,m.key)?.score??null})),metrics.map(m=>({key:m.key,label:m.label,score:get(right,m.key)?.score??null})));
  const leftAdvantages=outcomes.filter(o=>o.winner==="left").map(o=>o.label);const rightAdvantages=outcomes.filter(o=>o.winner==="right").map(o=>o.label);const winner=left.result.score===right.result.score?null:left.result.score>right.result.score?left:right;const difference=Math.abs(left.result.score-right.result.score);const selectClass="mt-2 w-full rounded-lg border border-slate-300 bg-white px-4 py-3 font-semibold text-slate-950";
  return <>
    <section className="mt-10 grid gap-4 border-y border-slate-200 py-5 md:grid-cols-[1fr_auto_1fr] md:items-end"><label className="text-sm font-semibold text-slate-700">First market<select value={left.slug} onChange={e=>changeComparison(e.target.value,right.slug)} className={selectClass}>{countries.map(c=><option key={c.slug} value={c.slug} disabled={c.slug===right.slug}>{c.name}</option>)}</select></label><span className="hidden pb-3 text-sm font-bold text-slate-400 md:block">VERSUS</span><label className="text-sm font-semibold text-slate-700">Second market<select value={right.slug} onChange={e=>changeComparison(left.slug,e.target.value)} className={selectClass}>{countries.map(c=><option key={c.slug} value={c.slug} disabled={c.slug===left.slug}>{c.name}</option>)}</select></label><div className="md:col-span-3"><SaveComparisonControl left={left.slug} right={right.slug} leftName={left.name} rightName={right.name}/></div></section>
    <section className="mt-10 overflow-x-auto"><div className="min-w-[640px]"><div className="grid grid-cols-[minmax(100px,1fr)_minmax(90px,1fr)_minmax(90px,1fr)_56px] items-end gap-3 border-b-2 border-slate-900 pb-4"><div className="text-xs font-bold uppercase tracking-[.12em] text-slate-500">Category</div>{[left,right].map(c=><div key={c.slug} className="flex items-center gap-3"><CountryFlag code={c.code} name={c.name} size="md"/><div><div className="font-bold">{c.name}</div><div className="text-xs text-slate-500">{c.result.confidence} confidence</div></div></div>)}<div className="text-right text-xs font-bold uppercase tracking-[.12em] text-slate-500">Winner</div></div>
      <ComparisonMetric label="Opportunity score" leftValue={`${left.result.score} · ${left.result.label}`} rightValue={`${right.result.score} · ${right.result.label}`} leftScore={left.result.score} rightScore={right.result.score} leftLabel={left.name} rightLabel={right.name}/>
      {metrics.map(m=>{const lf=get(left,m.key),rf=get(right,m.key);return lf&&rf?<ComparisonMetric key={m.key} label={m.label} leftValue={`${description(lf.score)} · ${lf.score}`} rightValue={`${description(rf.score)} · ${rf.score}`} leftScore={lf.score} rightScore={rf.score} leftLabel={left.name} rightLabel={right.name}/>:null})}
    </div></section>
    <section className="mt-12 border-t border-slate-200 pt-10"><p className="product-eyebrow">Decision brief</p><h2 className="mt-3 text-3xl font-bold">{winner?`${winner.name} leads this comparison.`:"The markets are tied."}</h2><p className="mt-3 max-w-3xl leading-7 text-slate-600">{winner?`${winner.name} leads by ${difference} SEKUR Score ${difference===1?"point":"points"}. Your strongest choice still depends on which trade-offs matter most to you.`:"Both markets currently have the same overall SEKUR Score."}</p><div className="mt-8 grid gap-8 md:grid-cols-2"><div><h3 className="text-lg font-bold">Why {left.name} may be better</h3><ul className="mt-3 space-y-2 text-slate-600">{leftAdvantages.length?leftAdvantages.map(a=><li key={a}>{a}</li>):<li>No significant category advantage detected.</li>}</ul></div><div><h3 className="text-lg font-bold">When {right.name} may be better</h3><ul className="mt-3 space-y-2 text-slate-600">{rightAdvantages.length?rightAdvantages.map(a=><li key={a}>{a}</li>):<li>No significant category advantage detected.</li>}</ul></div></div></section>
  </>;
}
