import test from "node:test"; import assert from "node:assert/strict"; import {readFileSync} from "node:fs"; import {resolveEntitlements} from "../lib/personalization/entitlements.ts"; import {validateAlertPreferences} from "../lib/personalization/alerts.ts"; import {sanitizeAnalyticsPayload} from "../lib/personalization/analytics.ts"; import {buildCareerSwitchPlan} from "../lib/personalization/careerSwitch.ts"; import {buildSalaryNegotiationReport} from "../lib/personalization/salaryNegotiation.ts"; import {getCareerCountryProfiles,getCareerCountryProfile} from "../lib/careerCountryProfiles.ts"; import type {CareerProfile} from "../lib/careerModel.ts"; import {convertCurrency} from "../lib/currency.ts";

test("Free and Pro capabilities gate monetization features",()=>{const free=resolveEntitlements("free"),pro=resolveEntitlements("pro");assert.equal(free.basicReport,true);assert.equal(free.careerSwitchPlanner,false);assert.equal(free.salaryNegotiationReport,false);assert.equal(free.alerts,false);assert.equal(pro.careerSwitchPlanner,true);assert.equal(pro.salaryNegotiationReport,true);assert.equal(pro.deepFactorBreakdown,true)});
test("alert preferences validate supported nonempty selections",()=>{assert.deepEqual(validateAlertPreferences(["salary_updated","salary_updated"]),["salary_updated"]);assert.throws(()=>validateAlertPreferences([]),/at least one/);assert.throws(()=>validateAlertPreferences(["email_everything"]),/Unsupported/)});
test("alert storage remains per-user and defaults future subscriptions off",()=>{const base=readFileSync(new URL("../supabase/migrations/20260815_create_user_career_intelligence.sql",import.meta.url),"utf8");const correction=readFileSync(new URL("../supabase/migrations/20260817_add_monetization_alert_preferences.sql",import.meta.url),"utf8");assert.match(base,/career_alert_subscriptions for all to authenticated using \(user_id = auth\.uid\(\)\) with check \(user_id = auth\.uid\(\)\)/);assert.match(correction,/alter column active set default false/);assert.doesNotMatch(correction,/service_role|grant .*anon/i)});
test("career switch preserves missing evidence rather than fabricating gaps",()=>{const careers=[{slug:"mechanical-engineer",title:"Mechanical Engineer",skills:["CAD"],aiRisk:"Low",remote:"Medium"},{slug:"software-engineer",title:"Software Engineer",skills:["JavaScript"],aiRisk:"Medium",remote:"High"}] as CareerProfile[];const plan=buildCareerSwitchPlan({currentCareerSlug:"mechanical-engineer",targetCareerSlug:"software-engineer",currentCountrySlug:"sweden",targetCountrySlug:"canada",skills:["CAD"],educationLevel:null,yearsExperience:2,timeHorizon:"12 months"},careers,getCareerCountryProfiles("mechanical-engineer"));assert.equal(plan.targetMarket,null);assert.equal(plan.salaryDifference,null);assert.equal(plan.confidence,"insufficient");assert.match(plan.limitations.join(" "),/unavailable/)});
test("salary negotiation uses native evidence and keeps FX display-only",()=>{const market=getCareerCountryProfile("mechanical-engineer","sweden")!;const report=buildSalaryNegotiationReport(market,621600);assert.equal(report.status,"ready");assert.equal(report.market?.salary.sourceCurrency,"SEK");const converted=convertCurrency(621600,"SEK","INR",{USD:1,SEK:10,INR:80});assert.equal(converted,4972800);assert.equal(market.salary.typical,621600)});
test("analytics payload strips private and unexpected fields",()=>{assert.deepEqual(sanitizeAnalyticsPayload({feature:"alerts",careerSlug:"accountant",skills:["secret"],email:"x@example.com",desiredSalary:500000}),{feature:"alerts",careerSlug:"accountant"})});
test("Opportunity Report locks deep output for Free users",()=>{const source=readFileSync(new URL("../components/user/OpportunityReportClient.tsx",import.meta.url),"utf8");assert.match(source,/deepFactors \? Object\.entries\(market\.factorBreakdown\)/);assert.match(source,/Detailed recommendations and factor evidence require Pro/)});
