import test from "node:test"; import assert from "node:assert/strict"; import {readFileSync} from "node:fs"; import {resolveEntitlements} from "../lib/personalization/entitlements.ts"; import {validateAlertPreferences} from "../lib/personalization/alerts.ts"; import {sanitizeAnalyticsPayload} from "../lib/personalization/analytics.ts"; import {buildCareerSwitchPlan} from "../lib/personalization/careerSwitch.ts"; import {buildSalaryNegotiationReport} from "../lib/personalization/salaryNegotiation.ts"; import {getCareerCountryProfiles,getCareerCountryProfile} from "../lib/careerCountryProfiles.ts"; import type {CareerProfile} from "../lib/careerModel.ts"; import {convertCurrency} from "../lib/currency.ts";
import type { CareerCountryProfile } from "../lib/careerCountryModel.ts";

test("Free and Pro capabilities gate monetization features",()=>{const free=resolveEntitlements("free"),pro=resolveEntitlements("pro");assert.equal(free.basicReport,true);assert.equal(free.careerSwitchPlanner,false);assert.equal(free.salaryNegotiationReport,false);assert.equal(free.alerts,false);assert.equal(free.personalizedJobMatch,false);assert.equal(pro.careerSwitchPlanner,true);assert.equal(pro.salaryNegotiationReport,true);assert.equal(pro.deepFactorBreakdown,true);assert.equal(pro.personalizedJobMatch,true);assert.equal(pro.opportunityMonitoring,true);assert.equal(pro.advancedActionPlan,true)});
test("alert preferences validate supported nonempty selections",()=>{assert.deepEqual(validateAlertPreferences(["salary_updated","salary_updated"]),["salary_updated"]);assert.throws(()=>validateAlertPreferences([]),/at least one/);assert.throws(()=>validateAlertPreferences(["email_everything"]),/Unsupported/)});
test("alert storage remains per-user and defaults future subscriptions off",()=>{const base=readFileSync(new URL("../supabase/migrations/20260815090200_create_user_career_intelligence.sql",import.meta.url),"utf8");const correction=readFileSync(new URL("../supabase/migrations/20260817090000_add_monetization_alert_preferences.sql",import.meta.url),"utf8");assert.match(base,/career_alert_subscriptions for all to authenticated using \(user_id = auth\.uid\(\)\) with check \(user_id = auth\.uid\(\)\)/);assert.match(correction,/alter column active set default false/);assert.doesNotMatch(correction,/service_role|grant .*anon/i)});
test("career switch preserves missing evidence rather than fabricating gaps",()=>{const careers=[{slug:"mechanical-engineer",title:"Mechanical Engineer",skills:["CAD"],aiRisk:"Low",remote:"Medium"},{slug:"software-engineer",title:"Software Engineer",skills:["JavaScript"],aiRisk:"Medium",remote:"High"}] as CareerProfile[];const plan=buildCareerSwitchPlan({currentCareerSlug:"mechanical-engineer",targetCareerSlug:"software-engineer",currentCountrySlug:"sweden",targetCountrySlug:"canada",skills:["CAD"],educationLevel:null,yearsExperience:2,timeHorizon:"12 months"},careers,getCareerCountryProfiles("mechanical-engineer"));assert.equal(plan.targetMarket,null);assert.equal(plan.salaryDifference,null);assert.equal(plan.confidence,"insufficient");assert.match(plan.limitations.join(" "),/unavailable/)});
test("salary negotiation uses native evidence and keeps FX display-only",()=>{const market=getCareerCountryProfile("mechanical-engineer","sweden")!;const report=buildSalaryNegotiationReport(market,621600);assert.equal(report.status,"ready");assert.equal(report.market?.salary.sourceCurrency,"SEK");const converted=convertCurrency(621600,"SEK","INR",{USD:1,SEK:10,INR:80});assert.equal(converted,4972800);assert.equal(market.salary.typical,621600)});
test("analytics payload strips private and unexpected fields",()=>{assert.deepEqual(sanitizeAnalyticsPayload({feature:"alerts",careerSlug:"accountant",skills:["secret"],email:"x@example.com",desiredSalary:500000}),{feature:"alerts",careerSlug:"accountant"})});
test("Opportunity Report keeps the explainable core available",()=>{const source=readFileSync(new URL("../components/user/OpportunityReportClient.tsx",import.meta.url),"utf8");assert.match(source,/Opportunity breakdown/);assert.match(source,/best\.scoreBreakdown\.components\.map/);assert.doesNotMatch(source,/Detailed recommendations and factor evidence require Pro/)});

test("salary negotiation preserves an hourly market benchmark", () => {
  const annual = getCareerCountryProfile("mechanical-engineer", "sweden")!;
  const hourly = { ...annual, countrySlug: "canada", salary: { ...annual.salary, low: 30, typical: 45.67, high: 72.49, sourceCurrency: "CAD", period: "hourly" as const } };
  const report = buildSalaryNegotiationReport(hourly, 45.67);
  assert.equal(report.position, "at the typical benchmark");
  assert.equal(report.market?.salary.period, "hourly");
  assert.deepEqual(report.discussionRange, { low: 45.67, high: 72.49 });
});

test("career switch refuses to subtract annual and hourly salaries", () => {
  const careers = [{ slug: "mechanical-engineer", title: "Mechanical Engineer", skills: [], aiRisk: "Low", remote: "Medium" }, { slug: "software-engineer", title: "Software Engineer", skills: [], aiRisk: "Medium", remote: "High" }] as unknown as CareerProfile[];
  const annual = getCareerCountryProfile("mechanical-engineer", "sweden")!;
  const hourly = { ...annual, careerSlug: "software-engineer", salary: { ...annual.salary, low: 30, typical: 45.67, high: 72.49, period: "hourly" as const } } as CareerCountryProfile;
  const plan = buildCareerSwitchPlan({ currentCareerSlug: "mechanical-engineer", targetCareerSlug: "software-engineer", currentCountrySlug: "sweden", targetCountrySlug: "sweden", skills: [], educationLevel: null, yearsExperience: null, timeHorizon: "12 months" }, careers, [annual, hourly]);
  assert.equal(plan.salaryDifference, null);
  assert.match(plan.limitations.join(" "), /different evidence periods/);
});
