import test from "node:test";
import assert from "node:assert/strict";
import type { CareerProfile } from "../lib/careerModel.ts";
import type { CareerCountryProfile } from "../lib/careerCountryModel.ts";
import type { CountryIntelligenceRow } from "../lib/intelligence/service.ts";
import type { JobPosting } from "../lib/jobs/types.ts";
import { buildBoundedCandidatePairs, findAdjacentCareers } from "../lib/opportunity/careerAdjacency.ts";
import { rankOpportunities, scoreOpportunity } from "../lib/opportunity/opportunityEngine.ts";

const career = (slug: string, title: string, category = "Engineering", skills = ["Python", "FEA"]): CareerProfile => ({ slug, title, category, score: 80, description: "", salary: null, hiring: "", layoffs: "", aiRisk: "", remote: "", education: null, workLife: "", demand: "", countries: [], skills, roadmap: [], courses: [], legacyCertifications: [], related: [] });
const market: CareerCountryProfile = { careerSlug: "mechanical-engineer", countrySlug: "sweden", salary: { low: 40000, typical: 60000, high: 80000, sourceCurrency: "SEK", period: "annual", geography: "Sweden", sourceName: "Official", sourceUrl: "https://example.test", observationDate: "2026", methodology: "Median", verificationStatus: "verified" }, hiringOutlook: { value: "Strong", sourceName: "Official", sourceUrl: "https://example.test", observationPeriod: "2026", verificationStatus: "verified" }, demand: { value: "Stable", sourceName: "Official", sourceUrl: "https://example.test", observationPeriod: "2026", verificationStatus: "verified" }, employmentRisk: { value: null, sourceName: null, sourceUrl: null, observationPeriod: null, verificationStatus: "needs-research" }, education: null, notes: [] };
const row = (factor_key: string, score: number): CountryIntelligenceRow => ({ id: 1, country_slug: "sweden", factor_key, factor_label: factor_key, score, weight: 1, source_type: "official", source_name: "Official", source_url: "https://example.test", explanation: null, verified_at: "2026-08-01", updated_at: "2026-08-01" });
const profile = { currentCareer: "mechanical-engineer", skills: ["Python"], currentCountry: null, targetCountries: ["sweden"], desiredSalary: 55000, desiredSalaryCurrency: "SEK", remotePreference: "neutral" as const };
const job: JobPosting = { id: "fixture:1", provider: "jobtech", sourceName: "JobTech", sourceUrl: "https://example.test/job", title: "Mechanical Engineer", company: "Example", countryCode: "SE", countryName: "Sweden", city: "Stockholm", locationText: "Stockholm", workplaceType: null, employmentType: null, description: "Python and FEA", skills: ["Python", "FEA"], publishedAt: "2026-08-01", expiresAt: null, salaryMin: null, salaryMax: null, salaryCurrency: null, salaryPeriod: null, applyUrl: "https://example.test/job", originalUrl: "https://example.test/job", careerSlug: "mechanical-engineer", providerMetadata: {} };

test("career adjacency is deterministic, explainable, and bounded", () => { const source = career("mechanical-engineer", "Mechanical Engineer"); const items = findAdjacentCareers(source, [source, career("test-engineer", "Test Engineer", "Engineering", ["FEA"]), career("accountant", "Accountant", "Finance", ["Tax"]), career("validation-engineer", "Validation Engineer", "Engineering", ["Python"])], 1); assert.equal(items.length, 1); assert.ok(items[0].reasons.length > 0); });
test("candidate generation filters countries and enforces the hard bound", () => { const careers = Array.from({ length: 20 }, (_, index) => career(`career-${index}`, `Career ${index}`)); const pairs = buildBoundedCandidatePairs(careers, (slug) => ["sweden", "germany", "united-states"].map((countrySlug) => ({ ...market, careerSlug: slug, countrySlug })), ["sweden", "germany"], 100); assert.equal(pairs.length, 40); assert.ok(pairs.every((item) => item.market.countrySlug !== "united-states")); });
test("general scoring is labelled non-personalized", () => { const result = scoreOpportunity({ profile: null, career: career("mechanical-engineer", "Mechanical Engineer"), market, countryName: "Sweden", countryCode: "SE" }); assert.equal(result.personalized, false); assert.equal(result.factors.find((item) => item.key === "liveJobs")?.score, null); });
test("country preferences alone do not claim personalization", () => { const result = scoreOpportunity({ profile: { ...profile, currentCareer: null, skills: [] }, career: career("mechanical-engineer", "Mechanical Engineer"), market, countryName: "Sweden", countryCode: "SE" }); assert.equal(result.personalized, false); });
test("complete available evidence produces visible coverage, confidence, and explanations", () => { const result = scoreOpportunity({ profile, career: career("mechanical-engineer", "Mechanical Engineer"), market, countryName: "Sweden", countryCode: "SE", countryRows: [row("safety", 90), row("cost_of_living", 55), row("visa", 75), row("healthcare", 85)], jobs: [job], liveJobTotal: 12 }); assert.equal(result.evidenceCoverage, 85); assert.equal(result.confidence, "high"); assert.equal(typeof result.opportunityScore, "number"); assert.ok(result.strengths.length); assert.ok(result.tradeoffs.some((item) => item.includes("Cost-of-living"))); assert.equal(result.scoreBreakdown.scoreVersion, "1.0"); });
test("missing factors remain unavailable and reduce confidence", () => { const result = scoreOpportunity({ profile: null, career: career("mechanical-engineer", "Mechanical Engineer"), market: { ...market, hiringOutlook: { ...market.hiringOutlook, value: null }, demand: { ...market.demand, value: null } }, countryName: "Sweden", countryCode: "SE" }); assert.equal(result.opportunityScore, null); assert.equal(result.confidence, "limited"); assert.ok(result.missingData.includes("Job-market demand")); });
test("unsupported live jobs are missing evidence rather than zero", () => { const result = scoreOpportunity({ profile, career: career("mechanical-engineer", "Mechanical Engineer"), market, countryName: "Germany", countryCode: "DE", liveJobTotal: null }); const live = result.factors.find((item) => item.key === "liveJobs"); assert.equal(live?.score, null); assert.match(live?.explanation ?? "", /unavailable/); });
test("low coverage cannot become a definitive score", () => { const sparse = { ...market, hiringOutlook: { ...market.hiringOutlook, value: null }, demand: { ...market.demand, value: null } }; const result = scoreOpportunity({ profile: null, career: career("mechanical-engineer", "Mechanical Engineer"), market: sparse, countryName: "Sweden", countryCode: "SE" }); assert.equal(result.evidenceCoverage, 16); assert.equal(result.opportunityScore, null); });
test("coverage penalty prevents sparse favorable evidence from dominating", () => { const full = scoreOpportunity({ profile, career: career("mechanical-engineer", "Mechanical Engineer"), market, countryName: "Sweden", countryCode: "SE", countryRows: [row("safety", 75), row("cost_of_living", 75), row("visa", 75), row("healthcare", 75)], jobs: [job], liveJobTotal: 5 }); const sparse = scoreOpportunity({ profile, career: { ...career("mechanical-engineer", "Mechanical Engineer"), score: 100 }, market: { ...market, hiringOutlook: { ...market.hiringOutlook, value: null }, demand: { ...market.demand, value: null } }, countryName: "Germany", countryCode: "DE" }); assert.ok((full.opportunityScore ?? 0) > (sparse.opportunityScore ?? 0)); });
test("skill gaps link only to verified study resources", () => { const result = scoreOpportunity({ profile, career: career("mechanical-engineer", "Mechanical Engineer"), market, countryName: "Sweden", countryCode: "SE", jobs: [job], liveJobTotal: 1 }); assert.ok(result.missingSkills.includes("FEA")); assert.equal(result.studyRecommendations[0].resource.provider, "Ansys"); });
test("ranking is stable, bounded, and leaves insufficient candidates unranked", () => { const base = scoreOpportunity({ profile, career: career("mechanical-engineer", "Mechanical Engineer"), market, countryName: "Sweden", countryCode: "SE" }); const ranked = rankOpportunities([{ ...base, countrySlug: "sweden", opportunityScore: 70 }, { ...base, countrySlug: "germany", opportunityScore: 70 }, { ...base, countrySlug: "united-states", opportunityScore: null }], 2); assert.deepEqual(ranked.map((item) => item.countrySlug), ["germany", "sweden"]); assert.equal(ranked.length, 2); });
