import test from "node:test";
import assert from "node:assert/strict";
import { calculateOpportunityScore, clampScore } from "../lib/scoring/opportunityScore.ts";
import { compareScoreRecords } from "../lib/scoring/comparison.ts";
import type { OpportunityScoreInput, SekurScoreKey } from "../lib/scoring/types.ts";

const keys: SekurScoreKey[] = ["careerFit", "countryFit", "jobMarketDemand", "salaryPotential", "costOfLivingEfficiency", "visaRelocationFeasibility", "safety", "skillsMatch", "experienceMatch", "educationMatch", "languageFit", "longTermGrowth"];
const input = (score: number | null): OpportunityScoreInput => Object.fromEntries(keys.map((key) => [key, { score, evidence: score === null ? "Unavailable" : "Fixture evidence" }])) as OpportunityScoreInput;

test("score normalization clamps values to 0-100", () => { assert.equal(clampScore(-12), 0); assert.equal(clampScore(101.4), 100); assert.equal(clampScore(77.6), 78); });
test("weighted scoring preserves a fully covered uniform score", () => { const result = calculateOpportunityScore(input(80)); assert.equal(result.overallScore, 80); assert.equal(result.evidenceCoverage, 100); assert.equal(result.confidence, "high"); });
test("missing evidence stays null and lowers coverage instead of becoming zero", () => { const values = input(null); values.careerFit = { score: 90, evidence: "Verified" }; const result = calculateOpportunityScore(values); assert.equal(result.overallScore, null); assert.equal(result.evidenceCoverage, 16); assert.ok(result.components.filter((item) => item.score === null).length > 0); });
test("partial profiles produce a qualified score only with enough evidence", () => { const values = input(null); values.careerFit = { score: 85, evidence: "Verified" }; values.jobMarketDemand = { score: 75, evidence: "Verified" }; values.safety = { score: 90, evidence: "Verified" }; values.skillsMatch = { score: 70, evidence: "Verified" }; const result = calculateOpportunityScore(values); assert.equal(result.evidenceCoverage, 48); assert.equal(result.confidence, "low"); assert.equal(typeof result.overallScore, "number"); });
test("strong and weak profiles remain ordered within score boundaries", () => { const strong = calculateOpportunityScore(input(90)); const weak = calculateOpportunityScore(input(35)); assert.ok((strong.overallScore ?? 0) > (weak.overallScore ?? 100)); assert.ok((strong.overallScore ?? 101) <= 100); assert.ok((weak.overallScore ?? -1) >= 0); });
test("explanations are structured from actual values", () => { const values = input(80); values.languageFit = { score: null, evidence: "Unavailable" }; values.costOfLivingEfficiency = { score: 40, evidence: "Verified" }; const result = calculateOpportunityScore(values); assert.ok(result.explanations.some((item) => item.kind === "positive")); assert.ok(result.explanations.some((item) => item.kind === "negative")); assert.ok(result.explanations.some((item) => item.kind === "missing" && item.factor === "languageFit")); });
test("comparison determines winners, ties, and unavailable categories", () => { const outcomes = compareScoreRecords([{ key: "salary", label: "Salary", score: 80 }, { key: "safety", label: "Safety", score: 90 }, { key: "visa", label: "Visa", score: null }], [{ key: "salary", label: "Salary", score: 70 }, { key: "safety", label: "Safety", score: 89 }, { key: "visa", label: "Visa", score: 80 }]); assert.deepEqual(outcomes.map((item) => item.winner), ["left", "tie", "unavailable"]); });
test("scoring version makes recomputation reproducible", () => { assert.equal(calculateOpportunityScore(input(75)).scoreVersion, "1.1"); });
