"use client";
import type { User } from "@supabase/supabase-js";
import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import type { CareerProfile } from "@/lib/careerModel";
import type { UserCareerProfile } from "@/lib/personalization/model";
import type { OpportunityResponse } from "@/lib/opportunity/types";
import SaveIntelligenceControl from "./SaveIntelligenceControl";
import CareerPathArt from "@/components/brand/CareerPathArt";

const emptyProfile:UserCareerProfile={currentCountry:null,targetCountries:["sweden","germany","united-states"],currentCareer:null,yearsExperience:null,educationLevel:null,skills:[],desiredSalary:null,desiredSalaryCurrency:null,remotePreference:"neutral",relocationWillingness:"maybe",careerGoals:null};
const countryNames:Record<string,string>={sweden:"Sweden",germany:"Germany","united-states":"United States"};
export default function OpportunityReportClient({user,careers}:{user:User|null;careers:CareerProfile[]}){
  const [profile,setProfile]=useState(emptyProfile);const [skillsText,setSkillsText]=useState("");const [report,setReport]=useState<OpportunityResponse|null>(null);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
  // Initialization intentionally runs only when the authenticated user changes.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{async function initialize(){let next=emptyProfile;if(user){const result=await supabase.from("user_career_profiles").select("*").eq("user_id",user.id).maybeSingle();if(result.data)next={currentCountry:result.data.current_country,targetCountries:result.data.target_countries?.length?result.data.target_countries:emptyProfile.targetCountries,currentCareer:result.data.current_career,yearsExperience:result.data.years_experience,educationLevel:result.data.education_level,skills:result.data.skills??[],desiredSalary:result.data.desired_salary,desiredSalaryCurrency:result.data.desired_salary_currency,remotePreference:result.data.remote_preference,relocationWillingness:result.data.relocation_willingness,careerGoals:result.data.career_goals}}setProfile(next);setSkillsText(next.skills.join(", "));await generate(next,false);setLoading(false)}void initialize()},[user]);
  async function generate(input=profile,save=true){setMessage("");try{const{data:sessionData}=await supabase.auth.getSession();const accessToken=sessionData.session?.access_token;const response=await fetch("/api/opportunities/recommend",{method:"POST",headers:{"Content-Type":"application/json",...(accessToken?{Authorization:`Bearer ${accessToken}`}:{})},body:JSON.stringify({profile:input.currentCareer||input.skills.length?{...input,skills:input.skills}:null,countries:input.targetCountries,limit:5})});const data=await response.json();if(!response.ok){setMessage(data.error??"Could not generate opportunities.");return}setReport(data);if(save&&user){const{error}=await supabase.from("career_opportunity_reports").insert({user_id:user.id,status:"ready",input_snapshot:input,output_snapshot:data,methodology_version:data.methodologyVersion,evidence_researched_at:data.generatedAt});setMessage(error?"Recommendations generated; the private snapshot could not be saved.":"Recommendations updated and saved privately.")}}catch{setMessage("Could not generate opportunities right now. Please try again.")}}
  function applyInputs(){const next={...profile,skills:skillsText.split(",").map(skill=>skill.trim()).filter(Boolean).slice(0,100)};setProfile(next);void generate(next)}
  if(loading)return <div className="border-y border-slate-200 py-8 text-slate-500">Calculating evidence-backed opportunities…</div>;
  const isPersonal=Boolean(profile.currentCareer||profile.skills.length);const recommendations=report?.recommendations??[];const best=recommendations[0];const alternatives=recommendations.slice(1);const control="mt-2 w-full rounded-lg border border-slate-300 bg-white px-4 py-3 text-slate-950";
  return <div className="mx-auto max-w-6xl">
    <header className="grid gap-8 border-b border-slate-200 pb-8 md:grid-cols-[1fr_300px] md:items-center"><div><p className="product-eyebrow">Opportunity report</p><h1 className="mt-3 text-4xl font-bold sm:text-5xl">Your career decision brief.</h1><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-600">A ranked view of career-market opportunities using available profile, market and live-job evidence. Missing evidence remains visible and lowers confidence.</p></div><CareerPathArt variant="path" className="hidden w-full md:block" /></header>
    {!isPersonal&&<div className="mt-6 border-l-2 border-amber-500 bg-amber-50 p-5"><h2 className="font-bold text-amber-950">General market view</h2><p className="mt-1 text-sm text-amber-900">Add your current career and skills to make this report personal.</p><Link href="/profile" className="mt-3 inline-block text-sm font-bold text-blue-700">Complete your profile →</Link></div>}
    <details className="mt-6 border-y border-slate-200 py-5"><summary className="cursor-pointer font-semibold text-slate-700">Adjust report inputs</summary><div className="mt-5 grid gap-5 md:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Current career<select value={profile.currentCareer??""} onChange={e=>setProfile({...profile,currentCareer:e.target.value||null})} className={control}><option value="">General market view</option>{careers.map(c=><option key={c.slug} value={c.slug}>{c.title}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">Skills<input value={skillsText} onChange={e=>setSkillsText(e.target.value)} placeholder="CAD, Python, SQL…" className={control}/></label><fieldset className="md:col-span-2"><legend className="text-sm font-semibold text-slate-700">Countries to consider</legend><div className="mt-3 flex flex-wrap gap-5">{Object.entries(countryNames).map(([slug,name])=><label key={slug} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={profile.targetCountries.includes(slug)} onChange={e=>setProfile({...profile,targetCountries:e.target.checked?[...profile.targetCountries,slug]:profile.targetCountries.filter(item=>item!==slug)})}/>{name}</label>)}</div></fieldset></div><button onClick={applyInputs} className="product-button product-button-primary mt-5">Recalculate report</button></details>
    {message&&<p role="status" className="mt-5 border-l-2 border-blue-600 bg-blue-50 p-4 text-sm text-slate-700">{message}</p>}
    {report?.accessLevel==="preview"&&<div className="mt-6 border-l-2 border-amber-500 bg-amber-50 p-5 text-sm text-amber-900"><strong>Opportunity preview</strong><p className="mt-1">Pro unlocks all 12 dimensions, job evidence, missing-skills analysis and the detailed action plan.</p><Link href="/pro" className="mt-2 inline-block font-bold text-blue-700">Explore SEKUR Pro →</Link></div>}
    {best&&<article className="mt-12">
      <div className="grid gap-8 border-b-2 border-slate-900 pb-8 md:grid-cols-[1fr_auto] md:items-end"><div><p className="product-eyebrow">Your best opportunity</p><h2 className="mt-3 text-4xl font-bold sm:text-5xl">{best.careerName}</h2><p className="mt-2 text-2xl text-slate-600">{best.countryName}</p></div><div className="grid grid-cols-3 gap-6 text-right"><div><div className="text-4xl font-bold">{best.opportunityScore??"—"}</div><div className="mt-1 text-xs text-slate-500">Score / 100</div></div><div><div className="text-lg font-bold capitalize">{best.confidence.replace("-"," ")}</div><div className="mt-1 text-xs text-slate-500">Confidence</div></div><div><div className="text-lg font-bold">{best.evidenceCoverage}%</div><div className="mt-1 text-xs text-slate-500">Coverage</div></div></div></div>
      <section className="mt-8"><h3 className="text-xl font-bold">Opportunity breakdown</h3><div className="mt-4 border-t border-slate-200">{best.scoreBreakdown.components.map(item=><div key={item.key} className="grid grid-cols-[minmax(120px,220px)_70px_1fr] gap-4 border-b border-slate-200 py-3 text-sm"><span className="font-semibold text-slate-700">{item.label}</span><span className="font-bold text-slate-950">{item.score??"—"}</span><span className="text-slate-500">{item.evidence}</span></div>)}</div><p className="mt-3 text-xs text-slate-500">Score version {best.scoreBreakdown.scoreVersion}. Unavailable evidence is excluded and lowers confidence.</p></section>
      <div className="mt-10 grid gap-10 md:grid-cols-2"><section><h3 className="text-xl font-bold">Why this fits you</h3><ol className="mt-4 space-y-3 text-slate-600">{best.strengths.length?best.strengths.map((item,index)=><li key={item}><span className="mr-3 font-bold text-blue-700">{index+1}.</span>{item}</li>):<li>Limited positive evidence is available.</li>}</ol></section><section><h3 className="text-xl font-bold">Your barriers</h3><ul className="mt-4 space-y-3 text-slate-600">{best.tradeoffs.length?best.tradeoffs.map(item=><li key={item}>{item}</li>):<li>No material trade-off was identified from available evidence.</li>}</ul></section></div>
      {best.actionPlan.length>0&&<section className="mt-10 border-y border-slate-200 py-8"><p className="product-eyebrow">Next best action</p><h3 className="mt-2 text-2xl font-bold">{best.actionPlan[0].action}</h3><div className="mt-6 grid gap-5 md:grid-cols-3">{best.actionPlan.map((item,index)=><div key={`${item.horizon}:${item.action}`}><div className="text-xs font-bold uppercase tracking-[.12em] text-slate-500">{index===0?"Start here":item.horizon.replaceAll("-"," ")}</div><p className="mt-2 text-sm leading-6 text-slate-700">{item.action}</p></div>)}</div></section>}
      {(best.existingSkills.length>0||best.missingSkills.length>0)&&<section className="mt-10 grid gap-8 md:grid-cols-2"><div><h3 className="font-bold">Your advantages</h3><p className="mt-2 text-sm leading-6 text-slate-600">{best.existingSkills.join(", ")||"Add profile skills to calculate this."}</p></div><div><h3 className="font-bold">High-value skill gaps</h3><p className="mt-2 text-sm leading-6 text-slate-600">{best.missingSkills.join(", ")||"No mapped gap identified."}</p>{best.studyRecommendations.map(({resource,matchedSkills})=><a key={resource.id} href={resource.url} target="_blank" rel="noopener noreferrer" className="mt-2 block text-sm font-semibold text-blue-700">Learn {matchedSkills.join(", ")} with {resource.provider} →</a>)}</div></section>}
      <div className="mt-10 flex flex-wrap items-center gap-5"><Link href={`/jobs?country=${best.countrySlug}&career=${best.careerSlug}`} className="product-button product-button-primary">{best.liveJobCount!==null?`View ${best.liveJobCount} matching jobs`:"Explore job coverage"}</Link><Link href={`/careers/${best.careerSlug}?country=${best.countrySlug}`} className="text-sm font-semibold text-blue-700">Career detail</Link><Link href={`/compare?left=${best.countrySlug}&right=${best.countrySlug==="sweden"?"germany":"sweden"}`} className="text-sm font-semibold text-blue-700">Compare market</Link><SaveIntelligenceControl itemType="career_market" careerSlug={best.careerSlug} countrySlug={best.countrySlug} label="Save opportunity"/></div>
      <details className="mt-8 border-t border-slate-200 pt-5"><summary className="cursor-pointer text-sm font-semibold text-slate-600">Evidence, live jobs and provenance</summary><div className="mt-5 space-y-4 text-sm text-slate-600">{best.representativeJobs.map(job=><a key={job.id} href={job.applyUrl} target="_blank" rel="noopener noreferrer" className="block border-b border-slate-200 pb-3"><strong>{job.title}</strong><span className="ml-2">{job.company} · {job.locationText}</span></a>)}</div></details>
    </article>}
    {alternatives.length>0&&<section className="mt-14 border-t border-slate-200 pt-10"><h2 className="text-2xl font-bold">Alternative opportunities</h2><div className="mt-5 divide-y divide-slate-200 border-y border-slate-200">{alternatives.map(candidate=><div key={`${candidate.countrySlug}:${candidate.careerSlug}`} className="grid gap-4 py-5 sm:grid-cols-[52px_1fr_auto] sm:items-center"><div className="text-sm font-bold text-slate-500">#{candidate.ranking??"—"}</div><div><h3 className="font-bold">{candidate.careerName}</h3><p className="mt-1 text-sm text-slate-500">{candidate.countryName} · <span className="capitalize">{candidate.confidence.replace("-"," ")}</span> confidence · {candidate.evidenceCoverage}% coverage</p></div><div className="flex items-center gap-4"><strong className="text-2xl">{candidate.opportunityScore??"—"}</strong><Link href={`/careers/${candidate.careerSlug}?country=${candidate.countrySlug}`} className="text-sm font-semibold text-blue-700">View</Link></div></div>)}</div></section>}
    <p className="mt-8 text-xs text-slate-500">Methodology {report?.methodologyVersion}</p>
  </div>;
}
