"use client";

import type { User } from "@supabase/supabase-js";
import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import type { CareerProfile } from "@/lib/careerModel";
import type { UserCareerProfile } from "@/lib/personalization/model";
import type { OpportunityResponse } from "@/lib/opportunity/types";
import SaveIntelligenceControl from "./SaveIntelligenceControl";

const emptyProfile: UserCareerProfile = { currentCountry: null, targetCountries: ["sweden", "germany", "united-states"], currentCareer: null, yearsExperience: null, educationLevel: null, skills: [], desiredSalary: null, desiredSalaryCurrency: null, remotePreference: "neutral", relocationWillingness: "maybe", careerGoals: null };
const countryNames: Record<string, string> = { sweden: "Sweden", germany: "Germany", "united-states": "United States" };

export default function OpportunityReportClient({ user, careers }: { user: User | null; careers: CareerProfile[] }) {
  const [profile, setProfile] = useState(emptyProfile); const [skillsText, setSkillsText] = useState(""); const [report, setReport] = useState<OpportunityResponse | null>(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  // Initialization intentionally runs only when the authenticated user changes.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { async function initialize() { let next = emptyProfile; if (user) { const result = await supabase.from("user_career_profiles").select("*").eq("user_id", user.id).maybeSingle(); if (result.data) next = { currentCountry: result.data.current_country, targetCountries: result.data.target_countries?.length ? result.data.target_countries : emptyProfile.targetCountries, currentCareer: result.data.current_career, yearsExperience: result.data.years_experience, educationLevel: result.data.education_level, skills: result.data.skills ?? [], desiredSalary: result.data.desired_salary, desiredSalaryCurrency: result.data.desired_salary_currency, remotePreference: result.data.remote_preference, relocationWillingness: result.data.relocation_willingness, careerGoals: result.data.career_goals }; } setProfile(next); setSkillsText(next.skills.join(", ")); await generate(next, false); setLoading(false); } void initialize(); }, [user]);
  async function generate(input = profile, save = true) { setMessage(""); try { const { data: sessionData } = await supabase.auth.getSession(); const accessToken = sessionData.session?.access_token; const response = await fetch("/api/opportunities/recommend", { method: "POST", headers: { "Content-Type": "application/json", ...(accessToken ? { Authorization: `Bearer ${accessToken}` } : {}) }, body: JSON.stringify({ profile: input.currentCareer || input.skills.length ? { ...input, skills: input.skills } : null, countries: input.targetCountries, limit: 5 }) }); const data = await response.json(); if (!response.ok) { setMessage(data.error ?? "Could not generate opportunities."); return; } setReport(data); if (save && user) { const { error } = await supabase.from("career_opportunity_reports").insert({ user_id: user.id, status: "ready", input_snapshot: input, output_snapshot: data, methodology_version: data.methodologyVersion, evidence_researched_at: data.generatedAt }); setMessage(error ? "Recommendations generated; the private snapshot could not be saved." : "Recommendations updated and saved privately."); } } catch { setMessage("Could not generate opportunities right now. Please try again."); } }
  function applyInputs() { const next = { ...profile, skills: skillsText.split(",").map((skill) => skill.trim()).filter(Boolean).slice(0, 100) }; setProfile(next); void generate(next); }
  if (loading) return <div className="glass-panel rounded-3xl border p-8 text-slate-300">Calculating evidence-backed opportunities…</div>;
  const isPersonal = Boolean(profile.currentCareer || profile.skills.length);
  return <div><section className="max-w-4xl"><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-300">Personal Opportunity Engine</p><h1 className="mt-4 text-5xl font-black sm:text-7xl">Your next move,<br /><span className="text-blue-300">calculated.</span></h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-400">SEKUR combines your skills with verified career, country and live-job evidence to identify realistic opportunities—without guaranteeing employment or inventing missing data.</p></section>
    {!isPersonal && <section className="mt-8 rounded-3xl border border-amber-300/20 bg-amber-300/[0.06] p-6"><h2 className="text-xl font-black text-amber-100">Make SEKUR personal</h2><p className="mt-2 text-slate-300">These are general market recommendations. Add your current career and skills for personalized results.</p><Link href="/profile" className="mt-4 inline-block rounded-xl bg-white px-5 py-3 font-black text-slate-950">Complete profile →</Link></section>}
    <details className="glass-panel mt-8 rounded-3xl border p-6"><summary className="cursor-pointer text-lg font-black">Adjust recommendation inputs</summary><div className="mt-6 grid gap-5 md:grid-cols-2"><label className="text-sm font-bold text-slate-300">Current career<select value={profile.currentCareer ?? ""} onChange={(e) => setProfile({ ...profile, currentCareer: e.target.value || null })} className="glass-control mt-2 w-full rounded-xl px-4 py-3"><option value="">General market view</option>{careers.map((career) => <option key={career.slug} value={career.slug}>{career.title}</option>)}</select></label><label className="text-sm font-bold text-slate-300">Skills<input value={skillsText} onChange={(e) => setSkillsText(e.target.value)} placeholder="CAD, Python, SQL…" className="glass-control mt-2 w-full rounded-xl px-4 py-3" /></label><fieldset className="md:col-span-2"><legend className="text-sm font-bold text-slate-300">Countries to consider</legend><div className="mt-3 flex flex-wrap gap-3">{Object.entries(countryNames).map(([slug, name]) => <label key={slug} className="glass-subtle flex items-center gap-2 rounded-xl border px-4 py-3"><input type="checkbox" checked={profile.targetCountries.includes(slug)} onChange={(e) => setProfile({ ...profile, targetCountries: e.target.checked ? [...profile.targetCountries, slug] : profile.targetCountries.filter((item) => item !== slug) })} />{name}</label>)}</div></fieldset></div><button onClick={applyInputs} className="mt-6 rounded-xl bg-emerald-300 px-6 py-3 font-black text-slate-950">Calculate my opportunities</button></details>
    {message && <p role="status" className="mt-4 rounded-xl border border-white/10 p-4 text-sm text-slate-300">{message}</p>}
    <section className="mt-12"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-300">{report?.personalized ? "Personalized recommendation" : "General market recommendation"}</p><h2 className="mt-2 text-4xl font-black">Your Best Opportunities</h2></div><p className="text-xs text-slate-500">Methodology: {report?.methodologyVersion}</p></div>{report?.accessLevel === "preview" && <div className="mt-6 rounded-2xl border border-amber-300/20 bg-amber-300/[0.06] p-5"><strong className="text-amber-100">Opportunity preview</strong><p className="mt-1 text-sm text-slate-300">Pro unlocks all 12 dimensions, job evidence, missing-skills analysis and the detailed action plan.</p><Link href="/pro" className="mt-3 inline-block font-bold text-amber-200">Explore SEKUR Pro →</Link></div>}
      <div className="mt-7 space-y-6">{report?.recommendations.map((candidate) => <article key={`${candidate.countrySlug}:${candidate.careerSlug}`} className={candidate.ranking === 1 ? "rounded-[2rem] bg-gradient-to-br from-emerald-300/[0.1] via-white/[0.045] to-blue-300/[0.06] p-7 shadow-[0_24px_70px_rgba(0,0,0,0.2)] sm:p-10" : "rounded-3xl bg-white/[0.03] p-6 sm:p-8"}><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-sm font-bold text-emerald-300">{candidate.ranking ? `#${candidate.ranking} opportunity` : "Limited intelligence available"}</p><h3 className={candidate.ranking === 1 ? "mt-3 text-4xl font-black sm:text-5xl" : "mt-2 text-3xl font-black"}>{candidate.countryName}</h3><p className="mt-1 text-xl text-blue-200">{candidate.careerName}</p></div><div className="text-right">{candidate.opportunityScore === null ? <div className="text-lg font-black text-amber-200">No definitive score</div> : <><div className={candidate.ranking === 1 ? "text-6xl font-black text-emerald-300" : "text-5xl font-black text-emerald-300"}>{candidate.opportunityScore}</div><div className="text-xs uppercase tracking-wide text-slate-500">Opportunity Score / 100</div></>}<div className="mt-2 text-sm capitalize text-slate-400">{candidate.confidence.replace("-", " ")} confidence · {candidate.evidenceCoverage}% coverage</div></div></div>
        <div className="mt-7 grid gap-6 lg:grid-cols-2"><div><h4 className="font-black text-emerald-200">Why this opportunity</h4><ul className="mt-3 space-y-2 text-sm text-slate-300">{candidate.strengths.length ? candidate.strengths.map((item) => <li key={item}>✓ {item}</li>) : <li>Limited positive evidence is available.</li>}</ul></div><div><h4 className="font-black text-amber-200">Watch</h4><ul className="mt-3 space-y-2 text-sm text-slate-400">{candidate.tradeoffs.map((item) => <li key={item}>• {item}</li>)}</ul></div></div>
        <details className="mt-7 rounded-2xl border border-white/10 p-5"><summary className="cursor-pointer font-black">Why this score?</summary><p className="mt-3 text-sm text-slate-400">Version {candidate.scoreBreakdown.scoreVersion} · unavailable evidence is excluded and lowers confidence.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{candidate.scoreBreakdown.components.map((item) => <div key={item.key} className="rounded-xl bg-black/20 p-4"><div className="flex justify-between gap-3"><span className="font-bold">{item.label}</span><span className={item.score === null ? "text-slate-500" : "text-emerald-300"}>{item.score ?? "Unavailable"}</span></div><p className="mt-2 text-xs leading-5 text-slate-500">{item.evidence}</p></div>)}</div></details>
        {candidate.comparisonToTop && (candidate.comparisonToTop.improves.length > 0 || candidate.comparisonToTop.worsens.length > 0) && <div className="mt-6 grid gap-3 text-sm sm:grid-cols-2"><p><strong className="text-emerald-200">Improves:</strong> {candidate.comparisonToTop.improves.join(", ") || "No clear category advantage"}</p><p><strong className="text-amber-100">Trade-off:</strong> {candidate.comparisonToTop.worsens.join(", ") || "No material decline detected"}</p></div>}
        {candidate.ranking === 1 && candidate.actionPlan.length > 0 && <section className="mt-7"><h4 className="font-black">Recommended action plan</h4><ol className="mt-3 space-y-2 text-sm text-slate-300">{candidate.actionPlan.map((item, index) => <li key={`${item.horizon}:${item.action}`}><span className="mr-2 font-black text-emerald-300">{index + 1}.</span><span className="mr-2 capitalize text-blue-200">{item.horizon.replaceAll("-", " ")}:</span>{item.action}</li>)}</ol></section>}
        {(candidate.existingSkills.length > 0 || candidate.missingSkills.length > 0) && <div className="mt-7 grid gap-5 md:grid-cols-2"><div><h4 className="font-black">You already have</h4><p className="mt-2 text-sm text-emerald-200">{candidate.existingSkills.join(", ") || "Add profile skills to calculate this."}</p></div><div><h4 className="font-black">Improve</h4><p className="mt-2 text-sm text-amber-200">{candidate.missingSkills.join(", ") || "No mapped gap identified."}</p>{candidate.studyRecommendations.map(({ resource, matchedSkills }) => <a key={resource.id} href={resource.url} target="_blank" rel="noopener noreferrer" className="mt-2 block text-sm font-bold text-blue-300">Learn {matchedSkills.join(", ")} with {resource.provider} →</a>)}</div></div>}
        {candidate.representativeJobs.length > 0 && <details className="mt-7"><summary className="cursor-pointer font-bold text-slate-300">Representative live jobs</summary><div className="mt-3 grid gap-3 md:grid-cols-3">{candidate.representativeJobs.map((job) => <a key={job.id} href={job.applyUrl} target="_blank" rel="noopener noreferrer" className="rounded-xl bg-black/15 p-4 text-sm hover:bg-black/25"><strong>{job.title}</strong><span className="mt-1 block text-slate-500">{job.company} · {job.locationText}</span></a>)}</div></details>}
        <div className="mt-7"><Link href={`/jobs?country=${candidate.countrySlug}&career=${candidate.careerSlug}`} className="inline-block rounded-xl bg-emerald-300 px-6 py-3 font-black text-slate-950 transition hover:bg-emerald-200">{candidate.liveJobCount !== null ? `View ${candidate.liveJobCount} matching jobs →` : "Explore job coverage →"}</Link><details className="mt-5"><summary className="cursor-pointer text-sm font-bold text-slate-400">More actions</summary><div className="mt-4 flex flex-wrap items-center gap-x-6 gap-y-3 text-sm"><Link href={`/careers/${candidate.careerSlug}?country=${candidate.countrySlug}`} className="font-bold text-blue-300">Explore career</Link><Link href={`/countries/${candidate.countrySlug}`} className="font-bold text-blue-300">Explore country</Link><Link href={`/compare?left=${candidate.countrySlug}&right=${candidate.countrySlug === "sweden" ? "germany" : "sweden"}`} className="font-bold text-blue-300">Compare</Link><SaveIntelligenceControl itemType="career_market" careerSlug={candidate.careerSlug} countrySlug={candidate.countrySlug} label="Save opportunity" /></div></details></div>
      </article>)}</div></section>
  </div>;
}
