"use client";
import type { User } from "@supabase/supabase-js";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import type { UserCareerProfile } from "@/lib/personalization/model";
import { normalizeStringList, validateUserCareerProfile } from "@/lib/personalization/validation";
import { calculateProfileCompleteness } from "@/lib/personalization/profileCompleteness";

const emptyProfile:UserCareerProfile={currentCountry:null,targetCountries:[],currentCareer:null,yearsExperience:null,educationLevel:null,skills:[],desiredSalary:null,desiredSalaryCurrency:null,remotePreference:"neutral",relocationWillingness:"maybe",careerGoals:null};
export default function ProfileClient({user,careers,countries}:{user:User;careers:Array<{slug:string;title:string}>;countries:Array<{slug:string;name:string;currency:string}>}){
  const [profile,setProfile]=useState(emptyProfile);const [skillsText,setSkillsText]=useState("");const [languagesText,setLanguagesText]=useState("");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
  useEffect(()=>{supabase.from("user_career_profiles").select("*").eq("user_id",user.id).maybeSingle().then(({data,error})=>{if(error)setMessage(error.message);if(data){const loaded:UserCareerProfile={currentCountry:data.current_country,targetCountries:data.target_countries??[],currentCareer:data.current_career,yearsExperience:data.years_experience,educationLevel:data.education_level,skills:data.skills??[],desiredSalary:data.desired_salary,desiredSalaryCurrency:data.desired_salary_currency,remotePreference:data.remote_preference,relocationWillingness:data.relocation_willingness,careerGoals:data.career_goals,languages:data.languages??[],educationField:data.education_field,citizenshipRegion:data.citizenship_region,workAuthorizationStatus:data.work_authorization_status??"unknown"};setProfile(loaded);setSkillsText(loaded.skills.join(", "));setLanguagesText((loaded.languages??[]).join(", "))}setLoading(false)})},[user.id]);
  async function save(){setSaving(true);setMessage("");try{const next=validateUserCareerProfile({...profile,skills:normalizeStringList(skillsText.split(","),100),languages:normalizeStringList(languagesText.split(","),20)});const{error}=await supabase.from("user_career_profiles").upsert({user_id:user.id,current_country:next.currentCountry,target_countries:next.targetCountries,current_career:next.currentCareer,years_experience:next.yearsExperience,education_level:next.educationLevel,education_field:next.educationField,skills:next.skills,languages:next.languages??[],citizenship_region:next.citizenshipRegion,work_authorization_status:next.workAuthorizationStatus??"unknown",desired_salary:next.desiredSalary,desired_salary_currency:next.desiredSalaryCurrency,remote_preference:next.remotePreference,relocation_willingness:next.relocationWillingness,career_goals:next.careerGoals,updated_at:new Date().toISOString()});if(error)throw error;setProfile(next);setMessage("Profile saved securely.")}catch(error){setMessage(error instanceof Error?error.message:"Could not save profile.")}finally{setSaving(false)}}
  if(loading)return <div className="border-y border-slate-200 py-8 text-slate-500">Loading your profile…</div>;
  const field="mt-2 w-full rounded-lg border border-slate-300 bg-white px-4 py-3 text-slate-950";const label="text-sm font-semibold text-slate-700";const completeness=calculateProfileCompleteness(profile);
  return <section className="profile-form mx-auto max-w-5xl">
    <div className="grid gap-6 border-b border-slate-200 pb-6 md:grid-cols-[1fr_240px] md:items-end"><div><p className="product-eyebrow">Career profile</p><h1 className="mt-2 text-4xl font-bold">My Career</h1><p className="mt-2 max-w-2xl text-slate-600">Your career profile shapes SEKUR&apos;s recommendations.</p></div><div aria-label={`Profile completeness ${completeness.score}%`}><div className="flex items-end justify-between"><span className="text-sm font-semibold text-slate-600">Profile strength</span><span className="text-2xl font-bold">{completeness.score}%</span></div><div className="mt-2 h-1.5 bg-slate-200"><div className="h-full bg-blue-600" style={{width:`${completeness.score}%`}}/></div></div></div>
    {completeness.recommendation&&<div className="mt-6 border-l-2 border-blue-600 bg-blue-50 px-5 py-4"><p className="text-xs font-bold uppercase tracking-[.12em] text-blue-700">Highest-value missing information</p><p className="mt-1 text-sm text-slate-700">{completeness.recommendation}</p></div>}
    <div className="mt-6 divide-y divide-slate-200">
      <fieldset className="grid gap-6 py-8 md:grid-cols-[220px_1fr]"><legend className="contents"><span className="text-lg font-bold">Current position</span></legend><div className="grid gap-5 sm:grid-cols-2"><label className={label}>Current role<select value={profile.currentCareer??""} onChange={e=>setProfile({...profile,currentCareer:e.target.value||null})} className={field}><option value="">Not selected</option>{careers.map(c=><option key={c.slug} value={c.slug}>{c.title}</option>)}</select></label><label className={label}>Current country<select value={profile.currentCountry??""} onChange={e=>setProfile({...profile,currentCountry:e.target.value||null})} className={field}><option value="">Not selected</option>{countries.map(c=><option key={c.slug} value={c.slug}>{c.name}</option>)}</select></label><label className={label}>Years of experience<input type="number" min="0" max="80" value={profile.yearsExperience??""} onChange={e=>setProfile({...profile,yearsExperience:e.target.value?Number(e.target.value):null})} className={field}/></label><label className={label}>Education level<input value={profile.educationLevel??""} onChange={e=>setProfile({...profile,educationLevel:e.target.value||null})} placeholder="e.g. Bachelor's degree" className={field}/></label></div></fieldset>
      <fieldset className="grid gap-6 py-8 md:grid-cols-[220px_1fr]"><legend className="contents"><span className="text-lg font-bold">Skills</span></legend><div className="grid gap-5"><label className={label}>Skills<input value={skillsText} onChange={e=>setSkillsText(e.target.value)} placeholder="e.g. CAD, Python, project management" className={field}/></label><label className={label}>Domain or education field<input value={profile.educationField??""} onChange={e=>setProfile({...profile,educationField:e.target.value||null})} placeholder="e.g. Mechanical engineering" className={field}/></label></div></fieldset>
      <fieldset className="grid gap-6 py-8 md:grid-cols-[220px_1fr]"><legend className="contents"><span className="text-lg font-bold">Career direction</span></legend><div className="grid gap-5"><fieldset><legend className={label}>Target countries</legend><div className="mt-3 grid gap-x-5 gap-y-2 sm:grid-cols-3">{countries.map(country=><label key={country.slug} className="flex items-center gap-2 text-sm text-slate-700"><input type="checkbox" checked={profile.targetCountries.includes(country.slug)} onChange={e=>setProfile({...profile,targetCountries:e.target.checked?[...profile.targetCountries,country.slug]:profile.targetCountries.filter(slug=>slug!==country.slug)})}/>{country.name}</label>)}</div></fieldset><label className={label}>What are you working toward?<textarea rows={3} maxLength={2000} value={profile.careerGoals??""} onChange={e=>setProfile({...profile,careerGoals:e.target.value||null})} className={field}/></label><div className="grid gap-5 sm:grid-cols-2"><label className={label}>Desired annual salary<input type="number" min="0" value={profile.desiredSalary??""} onChange={e=>setProfile({...profile,desiredSalary:e.target.value?Number(e.target.value):null})} className={field}/></label><label className={label}>Salary currency<select value={profile.desiredSalaryCurrency??""} onChange={e=>setProfile({...profile,desiredSalaryCurrency:e.target.value||null})} className={field}><option value="">Select currency</option>{[...new Set(countries.map(c=>c.currency))].map(currency=><option key={currency}>{currency}</option>)}</select></label><label className={label}>Remote work<select value={profile.remotePreference} onChange={e=>setProfile({...profile,remotePreference:e.target.value as UserCareerProfile["remotePreference"]})} className={field}><option value="required">Required</option><option value="preferred">Preferred</option><option value="neutral">No preference</option></select></label><label className={label}>Relocation willingness<select value={profile.relocationWillingness} onChange={e=>setProfile({...profile,relocationWillingness:e.target.value as UserCareerProfile["relocationWillingness"]})} className={field}><option value="yes">Yes</option><option value="maybe">Maybe</option><option value="no">No</option></select></label></div></div></fieldset>
      <fieldset className="grid gap-6 py-8 md:grid-cols-[220px_1fr]"><legend className="contents"><span className="text-lg font-bold">Language &amp; eligibility</span></legend><div className="grid gap-5 sm:grid-cols-2"><label className={label}>Languages<input value={languagesText} onChange={e=>setLanguagesText(e.target.value)} placeholder="e.g. English, Swedish" className={field}/></label><label className={label}>Work authorization<select value={profile.workAuthorizationStatus??"unknown"} onChange={e=>setProfile({...profile,workAuthorizationStatus:e.target.value as UserCareerProfile["workAuthorizationStatus"]})} className={field}><option value="unknown">Not specified</option><option value="authorized">Authorized</option><option value="requires-sponsorship">Requires sponsorship</option><option value="not-authorized">Not authorized</option></select></label></div></fieldset>
    </div>
    {message&&<div role="status" className="border-l-2 border-blue-600 bg-blue-50 p-4 text-sm text-slate-700">{message}</div>}<div className="mt-6 flex flex-wrap items-center gap-5"><button type="button" onClick={save} disabled={saving} className="product-button product-button-primary disabled:opacity-50">{saving?"Saving…":"Save career profile"}</button><button type="button" onClick={()=>supabase.auth.signOut()} className="text-sm font-semibold text-slate-500">Sign out</button></div>
  </section>;
}
