import { CareerProfile } from "@/lib/careerModel";

const profiles: CareerProfile[] = [
  {
    slug: "mechanical-engineer",
    title: "Mechanical Engineer",
    category: "Engineering",
    score: 84,
    description:
      "Design, develop, test and improve mechanical products, machines and systems across automotive, energy, aerospace and manufacturing.",
    salary: {
      low: 68_740,
      typical: 102_320,
      high: 161_240,
      sourceCurrency: "USD",
      geography: "United States (national)",
      sourceName: "U.S. Bureau of Labor Statistics, Occupational Outlook Handbook — Mechanical Engineers",
      sourceUrl: "https://www.bls.gov/ooh/architecture-and-engineering/mechanical-engineers.htm",
      observationDate: "May 2024",
      methodology: "Annual wage distribution for U.S. mechanical engineers (SOC 17-2141): low is the BLS lower-10-percent cutoff, typical is the median, and high is the BLS upper-10-percent cutoff. Values are national and not adjusted for experience, industry, or local area.",
      verificationStatus: "verified",
    },
    hiring: "Stable",
    layoffs: "Low",
    aiRisk: "Low",
    remote: "Medium",
    education: {
      typicalEducation: "Bachelor's degree in mechanical engineering or mechanical engineering technology",
      degreeRequirement: "A bachelor's degree is typically needed. Entry-level licensure is not required, but engineers who offer services directly to the public must be licensed.",
      commonFields: ["Mechanical engineering", "Mechanical engineering technology"],
      alternativePathways: [
        "Five-year programs combining bachelor's and master's degrees",
        "Cooperative education programs combining classroom study with practical work",
        "Mechanical engineering technology bachelor's programs with a stronger applied focus",
      ],
      certifications: [
        "Fundamentals of Engineering (FE) exam / Engineer in Training (EIT) pathway",
        "Professional Engineer (PE) license for qualified, experienced engineers",
      ],
      verificationStatus: "verified",
    },
    workLife: "Good",
    demand: "Strong",
    countries: [
      { flag: "CH", country: "Switzerland", earningPotential: "Research required", demand: "Strong" },
      { flag: "US", country: "United States", earningPotential: "Research required", demand: "Strong" },
      { flag: "DE", country: "Germany", earningPotential: "Research required", demand: "Strong" },
      { flag: "SE", country: "Sweden", earningPotential: "Research required", demand: "Stable" },
      { flag: "CA", country: "Canada", earningPotential: "Research required", demand: "Strong" },
      { flag: "AU", country: "Australia", earningPotential: "Research required", demand: "Strong" },
    ],
    skills: ["CAD", "FEA", "Product Development", "Manufacturing", "Testing", "Materials", "Thermodynamics", "Problem Solving"],
    roadmap: [
      "Build strong mathematics and engineering fundamentals",
      "Learn CAD and engineering analysis tools",
      "Build practical projects and a technical portfolio",
      "Enter a graduate or junior engineering role",
      "Develop a technical specialization",
      "Progress to senior engineer or technical lead",
      "Move into management, consulting or entrepreneurship",
    ],
    courses: [
      { title: "CAD & Product Design", type: "Course" },
      { title: "Finite Element Analysis", type: "Course" },
      { title: "Python for Engineers", type: "Course" },
      { title: "Design for Manufacturing", type: "Course" },
    ],
    legacyCertifications: [],
    related: ["Automation Engineer", "Controls Engineer", "Manufacturing Engineer", "Product Development Engineer"],
  },
  {
    slug: "cybersecurity-analyst",
    title: "Cybersecurity Analyst",
    category: "Technology",
    score: 94,
    description:
      "Protect organizations, infrastructure and digital information from cyber threats, vulnerabilities and security incidents.",
    salary: {
      low: 69_660,
      typical: 124_910,
      high: 186_420,
      sourceCurrency: "USD",
      geography: "United States (national)",
      sourceName: "U.S. Bureau of Labor Statistics, Occupational Outlook Handbook — Information Security Analysts",
      sourceUrl: "https://www.bls.gov/ooh/computer-and-information-technology/information-security-analysts.htm",
      observationDate: "May 2024",
      methodology: "Annual wage distribution for U.S. information security analysts (SOC 15-1212), used as SEKUR's Cybersecurity Analyst benchmark: low is the BLS lower-10-percent cutoff, typical is the median, and high is the BLS upper-10-percent cutoff. Values are national and not adjusted for experience, industry, or local area.",
      verificationStatus: "verified",
    },
    hiring: "Very Strong",
    layoffs: "Low",
    aiRisk: "Low",
    remote: "High",
    education: {
      typicalEducation: "Bachelor's degree in computer and information technology or a related field, plus related work experience",
      degreeRequirement: "A bachelor's degree is typical, but not universal; BLS reports that some workers enter with a high school diploma plus relevant industry training and certifications.",
      commonFields: [
        "Computer and information technology",
        "Computer science",
        "Engineering",
        "Mathematics",
      ],
      alternativePathways: [
        "High school diploma plus relevant industry training and certifications",
        "Related IT experience, often in network and computer systems administration",
      ],
      certifications: [
        "ISC2 Certified in Cybersecurity (CC) — entry-level; no work experience required",
        "ISC2 CISSP — experienced practitioners; five years of qualifying experience is normally required",
      ],
      verificationStatus: "verified",
    },
    workLife: "Good",
    demand: "Very Strong",
    countries: [
      { flag: "US", country: "United States", earningPotential: "Research required", demand: "Very Strong" },
      { flag: "SG", country: "Singapore", earningPotential: "Research required", demand: "Very Strong" },
      { flag: "CH", country: "Switzerland", earningPotential: "Research required", demand: "Strong" },
      { flag: "DE", country: "Germany", earningPotential: "Research required", demand: "Strong" },
      { flag: "GB", country: "United Kingdom", earningPotential: "Research required", demand: "Strong" },
      { flag: "AU", country: "Australia", earningPotential: "Research required", demand: "Strong" },
    ],
    skills: ["Networking", "Linux", "Security Operations", "Cloud Security", "Incident Response", "Threat Analysis", "Python", "Risk Management"],
    roadmap: [
      "Learn IT and networking fundamentals",
      "Learn Linux and security basics",
      "Build a practical home lab",
      "Complete security projects",
      "Research role-appropriate credentials",
      "Enter a security operations or analyst role",
      "Specialize in security engineering or architecture",
    ],
    courses: [
      { title: "Cybersecurity Fundamentals", type: "Course" },
      { title: "Security Certification Preparation", type: "Certification" },
      { title: "Practical Security Labs", type: "Labs" },
      { title: "Cloud Security Fundamentals", type: "Course" },
    ],
    legacyCertifications: [],
    related: ["Cloud Security Engineer", "Security Engineer", "DevOps Engineer", "Network Engineer"],
  },
  {
    slug: "software-engineer",
    title: "Software Engineer",
    category: "Technology",
    score: 92,
    description: "Design and build software products, applications and digital systems used by businesses and consumers around the world.",
    salary: null,
    legacySalaryLabel: "$133k",
    hiring: "Strong",
    layoffs: "Medium",
    aiRisk: "Medium",
    remote: "High",
    education: null,
    legacyEducationLabel: "Degree Optional",
    workLife: "Good",
    demand: "Strong",
    countries: [
      { flag: "US", country: "United States", earningPotential: "$133k+", demand: "Strong" },
      { flag: "CH", country: "Switzerland", earningPotential: "Very High", demand: "Strong" },
      { flag: "SG", country: "Singapore", earningPotential: "High", demand: "Strong" },
      { flag: "DE", country: "Germany", earningPotential: "High", demand: "Strong" },
      { flag: "CA", country: "Canada", earningPotential: "High", demand: "Strong" },
      { flag: "AU", country: "Australia", earningPotential: "High", demand: "Strong" },
    ],
    skills: ["Programming", "Algorithms", "Git", "Databases", "APIs", "Cloud", "Testing", "System Design"],
    roadmap: ["Choose a programming language", "Learn programming fundamentals", "Build real projects", "Learn Git, databases and APIs", "Create a strong portfolio", "Apply for junior engineering roles", "Progress into specialization or technical leadership"],
    courses: [{ title: "Programming Fundamentals", type: "Course" }, { title: "Full Stack Development", type: "Course" }, { title: "Cloud Fundamentals", type: "Certification" }, { title: "System Design", type: "Course" }],
    legacyCertifications: ["Cloud certification", "Security fundamentals", "Database certification", "Platform-specific credentials"],
    related: ["DevOps Engineer", "Cloud Engineer", "Data Engineer", "Cybersecurity Analyst"],
  },
  {
    slug: "automation-engineer",
    title: "Automation Engineer",
    category: "Engineering",
    score: 90,
    description: "Design and improve automated machines, industrial systems, production lines and control solutions.",
    salary: null,
    legacySalaryLabel: "Researching",
    hiring: "Strong",
    layoffs: "Low",
    aiRisk: "Low",
    remote: "Medium",
    education: null,
    legacyEducationLabel: "Bachelor Degree",
    workLife: "Good",
    demand: "Strong",
    countries: [
      { flag: "DE", country: "Germany", earningPotential: "High", demand: "Very Strong" },
      { flag: "SE", country: "Sweden", earningPotential: "Competitive", demand: "Strong" },
      { flag: "CH", country: "Switzerland", earningPotential: "Very High", demand: "Strong" },
      { flag: "US", country: "United States", earningPotential: "High", demand: "Strong" },
      { flag: "NL", country: "Netherlands", earningPotential: "High", demand: "Strong" },
      { flag: "CA", country: "Canada", earningPotential: "Competitive", demand: "Strong" },
    ],
    skills: ["PLC", "Control Systems", "Industrial Automation", "Robotics", "Sensors", "Electrical Systems", "Python", "Troubleshooting"],
    roadmap: ["Build electrical and control-system fundamentals", "Learn PLC programming", "Understand sensors, actuators and industrial communication", "Build automation projects", "Enter an automation or controls engineering role", "Specialize in robotics, manufacturing or process automation", "Progress to technical lead, consultant or integrator"],
    courses: [{ title: "PLC Programming", type: "Course" }, { title: "Industrial Automation", type: "Course" }, { title: "Robotics Fundamentals", type: "Course" }, { title: "Control Systems", type: "Course" }],
    legacyCertifications: ["PLC vendor certification", "Industrial automation certification", "Robotics platform certification", "Functional safety training"],
    related: ["Controls Engineer", "Robotics Engineer", "Electrical Engineer", "Manufacturing Engineer"],
  },
];

export const careerProfiles: Record<string, CareerProfile> = Object.fromEntries(
  profiles.map((profile) => [profile.slug, profile])
);

export function getCareerProfile(slug: string) {
  return careerProfiles[slug] ?? null;
}
