import { createHmac, timingSafeEqual } from "node:crypto";
import type { BillingConfig } from "./config.ts";

type StripeSession = { id: string; url: string | null };
export function isStripeHostedUrl(value: string | null): value is string { if (!value) return false; try { const parsed = new URL(value); return parsed.protocol === "https:" && (parsed.hostname === "checkout.stripe.com" || parsed.hostname === "billing.stripe.com"); } catch { return false; } }
async function stripeRequest<T>(config: BillingConfig, path: string, body: URLSearchParams, fetcher: typeof fetch = fetch): Promise<T> { if (!config.secretKey) throw new Error("Stripe is not configured."); const response = await fetcher(`https://api.stripe.com/v1/${path}`, { method: "POST", headers: { Authorization: `Bearer ${config.secretKey}`, "Content-Type": "application/x-www-form-urlencoded" }, body }); const data = await response.json(); if (!response.ok) throw new Error(typeof data?.error?.message === "string" ? data.error.message : "Stripe request failed."); return data as T; }
export function createCheckoutSession(config: BillingConfig, input: { userId: string; email: string | null; customerId: string | null }, fetcher?: typeof fetch) { if (!config.proPriceId) throw new Error("Stripe Pro price is not configured."); const body = new URLSearchParams({ mode: "subscription", "line_items[0][price]": config.proPriceId, "line_items[0][quantity]": "1", success_url: `${config.appUrl}/pro?checkout=success`, cancel_url: `${config.appUrl}/pro?checkout=canceled`, client_reference_id: input.userId, "metadata[user_id]": input.userId, "subscription_data[metadata][user_id]": input.userId, allow_promotion_codes: "true" }); if (input.customerId) body.set("customer", input.customerId); else if (input.email) body.set("customer_email", input.email); return stripeRequest<StripeSession>(config, "checkout/sessions", body, fetcher); }
export function createPortalSession(config: BillingConfig, customerId: string, fetcher?: typeof fetch) { return stripeRequest<StripeSession>(config, "billing_portal/sessions", new URLSearchParams({ customer: customerId, return_url: `${config.appUrl}/pro` }), fetcher); }
export function verifyStripeSignature(payload: string, signatureHeader: string | null, secret: string | null, nowSeconds = Math.floor(Date.now() / 1000), toleranceSeconds = 300) { if (!signatureHeader || !secret) return false; const values = Object.fromEntries(signatureHeader.split(",").map((part) => part.split("=", 2) as [string, string])); const timestamp = Number(values.t); const signature = values.v1; if (!Number.isFinite(timestamp) || !signature || Math.abs(nowSeconds - timestamp) > toleranceSeconds) return false; const expected = createHmac("sha256", secret).update(`${timestamp}.${payload}`, "utf8").digest("hex"); const left = Buffer.from(signature); const right = Buffer.from(expected); return left.length === right.length && timingSafeEqual(left, right); }
