import { NextResponse } from "next/server";
import { resolveEntitlements } from "@/lib/personalization/entitlements";
import { authenticateRequest, createServiceRoleClient } from "@/lib/supabaseServer";
import { careerProfiles } from "@/lib/careerProfiles";

const slug = (value: unknown) => typeof value === "string" && /^[a-z0-9-]{1,80}$/.test(value) ? value : null;
const supportedCountries = new Set(["sweden", "germany", "united-states"]);
async function proAuth(request: Request) { const auth = await authenticateRequest(request); if (!auth) return null; const { data } = await auth.client.from("user_entitlements").select("plan_key,feature_overrides,valid_until").eq("user_id", auth.user.id).maybeSingle(); const expired = data?.valid_until && new Date(data.valid_until).getTime() < Date.now(); const allowed = !expired && resolveEntitlements(data?.plan_key, data?.feature_overrides ?? {}).opportunityMonitoring; return allowed ? auth : null; }
export async function GET(request: Request) { const auth = await proAuth(request); if (!auth) return NextResponse.json({ error: "Pro opportunity monitoring is required." }, { status: 403 }); const { data, error } = await auth.client.from("opportunity_watches").select("id,career_slug,country_slug,active,last_evaluated_at,last_score,last_score_version,created_at").eq("user_id", auth.user.id).order("created_at", { ascending: false }); return error ? NextResponse.json({ error: "Watches could not be loaded." }, { status: 503 }) : NextResponse.json({ watches: data ?? [] }); }
export async function POST(request: Request) { const auth = await proAuth(request); if (!auth) return NextResponse.json({ error: "Pro opportunity monitoring is required." }, { status: 403 }); const body = await request.json().catch(() => null); const careerSlug = slug(body?.careerSlug); const countrySlug = slug(body?.countrySlug); if (!careerSlug || !careerProfiles[careerSlug] || !countrySlug || !supportedCountries.has(countrySlug)) return NextResponse.json({ error: "A supported career and country are required." }, { status: 400 }); try { const service = createServiceRoleClient(); const { data, error } = await service.from("opportunity_watches").upsert({ user_id: auth.user.id, career_slug: careerSlug, country_slug: countrySlug, active: true }, { onConflict: "user_id,career_slug,country_slug" }).select("id,career_slug,country_slug,active").single(); return error ? NextResponse.json({ error: "Watch could not be saved." }, { status: 503 }) : NextResponse.json({ watch: data }); } catch { return NextResponse.json({ error: "Trusted monitoring persistence is not configured." }, { status: 503 }); } }
export async function DELETE(request: Request) { const auth = await proAuth(request); if (!auth) return NextResponse.json({ error: "Pro opportunity monitoring is required." }, { status: 403 }); const id = Number(new URL(request.url).searchParams.get("id")); if (!Number.isSafeInteger(id) || id <= 0) return NextResponse.json({ error: "A valid watch id is required." }, { status: 400 }); try { const service = createServiceRoleClient(); const { data, error } = await service.from("opportunity_watches").delete().eq("id", id).eq("user_id", auth.user.id).select("id").maybeSingle(); if (error) return NextResponse.json({ error: "Watch could not be deleted." }, { status: 503 }); if (!data) return NextResponse.json({ error: "Watch was not found." }, { status: 404 }); return NextResponse.json({ deleted: true }); } catch { return NextResponse.json({ error: "Trusted monitoring persistence is not configured." }, { status: 503 }); } }
