export type ExperienceRequirement = { minimumYears: number | null; preferredYears: number | null; seniority: "junior" | "mid" | "senior" | "lead" | null; leadershipRequired: boolean | null; domainExperience: string[]; evidenceText: string };
export type EducationRequirement = { minimumLevel: string | null; preferredLevel: string | null; fields: string[]; certifications: string[]; legallyRequired: boolean | null; recognitionRequired: boolean | null; evidenceText: string };

export function extractExperienceRequirement(text: string | null): ExperienceRequirement | null {
  if (!text) return null; const normalized = text.replace(/\s+/g, " "); const years = normalized.match(/(?:minimum(?: of)?\s*)?(\d{1,2})(?:\s*[-–]\s*(\d{1,2}))?\+?\s+years?(?:\s+of)?\s+(?:relevant\s+)?experience/i); const seniority = /\blead(?:er|ership)?\b/i.test(normalized) ? "lead" : /\bsenior\b/i.test(normalized) ? "senior" : /\bmid(?:-level)?\b/i.test(normalized) ? "mid" : /\bjunior\b|entry.level/i.test(normalized) ? "junior" : null; if (!years && !seniority) return null; return { minimumYears: years ? Number(years[1]) : null, preferredYears: years?.[2] ? Number(years[2]) : null, seniority, leadershipRequired: /leadership experience|required to lead/i.test(normalized) ? true : null, domainExperience: [], evidenceText: years?.[0] ?? seniority ?? "" };
}

export function calculateExperienceMatch(yearsExperience: number | null | undefined, requirement: ExperienceRequirement | null) {
  if (yearsExperience === null || yearsExperience === undefined || !requirement || requirement.minimumYears === null) return { score: null, explanation: "Comparable experience evidence is unavailable." };
  if (yearsExperience >= requirement.minimumYears) return { score: 100, explanation: `Your stated experience meets the sourced ${requirement.minimumYears}-year minimum.` };
  return { score: Math.max(20, Math.round(yearsExperience / requirement.minimumYears * 100)), explanation: `The source states ${requirement.minimumYears} years; your profile states ${yearsExperience}.` };
}

export function extractEducationRequirement(text: string | null): EducationRequirement | null { if (!text) return null; const match = text.match(/(?:required|must have|minimum of)?\s*(bachelor(?:'s)?|master(?:'s)?|doctorate|phd|diploma)(?:\s+degree)?(?:\s+in\s+([A-Za-z][A-Za-z &/-]{2,60}))?/i); if (!match) return null; return { minimumLevel: match[1], preferredLevel: null, fields: match[2] ? [match[2].trim()] : [], certifications: [], legallyRequired: null, recognitionRequired: null, evidenceText: match[0] }; }
const educationRank = (value: string) => /doctor|phd/i.test(value) ? 4 : /master/i.test(value) ? 3 : /bachelor|degree/i.test(value) ? 2 : /diploma|secondary|high school/i.test(value) ? 1 : null;
export function calculateEducationMatch(profileEducation: string | null | undefined, requirement: EducationRequirement | null) { if (!profileEducation || !requirement?.minimumLevel) return { score: null, explanation: "Comparable education evidence is unavailable." }; const profileRank = educationRank(profileEducation); const requiredRank = educationRank(requirement.minimumLevel); if (profileRank === null || requiredRank === null) return { score: null, explanation: "Education levels could not be compared safely." }; return profileRank >= requiredRank ? { score: 100, explanation: "Your stated education meets the sourced requirement." } : { score: 35, explanation: `The source states ${requirement.minimumLevel}; your profile states ${profileEducation}.` }; }
