import { supabase } from "../supabase.ts";
import type { LanguageEvidence } from "./language.ts";
import type { WorkAuthorizationEvidence } from "./workAuthorization.ts";
import type { EvidenceAuthority, EvidenceConfidence, EvidenceStatus } from "./types.ts";

type LanguageRow = { country_slug: string; career_slug: string | null; primary_workplace_language: string; useful_languages: string[]; english_only_realistic: boolean | null; local_language_importance: LanguageEvidence["localLanguageImportance"]; recommended_proficiency: string | null; requirement_level: LanguageEvidence["requirementLevel"]; source_name: string; source_url: string; source_authority: EvidenceAuthority; effective_from: string | null; reference_period: string | null; retrieved_at: string; confidence: EvidenceConfidence; review_status: EvidenceStatus };
type WorkRow = { origin_region: string; destination_country_slug: string; permit_requirement: WorkAuthorizationEvidence["permitRequirement"]; employer_sponsorship: WorkAuthorizationEvidence["employerSponsorship"]; job_offer_required: boolean | null; salary_threshold: number | null; salary_currency: string | null; salary_period: "annual" | "monthly" | null; qualification_requirement: string | null; occupation_restrictions: string[]; processing_complexity: WorkAuthorizationEvidence["processingComplexity"]; source_name: string; source_url: string; source_authority: EvidenceAuthority; effective_from: string | null; retrieved_at: string; confidence: EvidenceConfidence; review_status: EvidenceStatus };
export type PublishedOpportunityEvidence = { languages: Array<{ countrySlug: string; careerSlug: string | null; evidence: LanguageEvidence }>; workAuthorization: Array<{ originRegion: string; countrySlug: string; evidence: WorkAuthorizationEvidence }> };

export async function getPublishedOpportunityEvidence(): Promise<PublishedOpportunityEvidence> { const [languageResult, workResult] = await Promise.all([supabase.from("country_language_evidence").select("*").eq("review_status", "published"), supabase.from("work_authorization_evidence").select("*").eq("review_status", "published")]); const languages = ((languageResult.data ?? []) as LanguageRow[]).map((row) => ({ countrySlug: row.country_slug, careerSlug: row.career_slug, evidence: { primaryWorkplaceLanguage: row.primary_workplace_language, usefulLanguages: row.useful_languages, englishOnlyRealistic: row.english_only_realistic, localLanguageImportance: row.local_language_importance, recommendedProficiency: row.recommended_proficiency, requirementLevel: row.requirement_level, provenance: { sourceName: row.source_name, sourceUrl: row.source_url, authority: row.source_authority, retrievedAt: row.retrieved_at, effectiveFrom: row.effective_from, referencePeriod: row.reference_period, geography: row.country_slug, careerSlug: row.career_slug, confidence: row.confidence, status: row.review_status } } })); const workAuthorization = ((workResult.data ?? []) as WorkRow[]).map((row) => ({ originRegion: row.origin_region, countrySlug: row.destination_country_slug, evidence: { originRegion: row.origin_region, destinationCountry: row.destination_country_slug, permitRequirement: row.permit_requirement, employerSponsorship: row.employer_sponsorship, jobOfferRequired: row.job_offer_required, salaryThreshold: row.salary_threshold !== null && row.salary_currency && row.salary_period ? { amount: row.salary_threshold, currency: row.salary_currency, period: row.salary_period } : null, qualificationRequirement: row.qualification_requirement, occupationRestrictions: row.occupation_restrictions, processingComplexity: row.processing_complexity, provenance: { sourceName: row.source_name, sourceUrl: row.source_url, authority: row.source_authority, retrievedAt: row.retrieved_at, effectiveFrom: row.effective_from, referencePeriod: null, geography: row.destination_country_slug, careerSlug: null, confidence: row.confidence, status: row.review_status } } })); return { languages, workAuthorization }; }
