create table public.user_career_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  current_country text,
  target_countries text[] not null default '{}',
  current_career text,
  years_experience numeric check (years_experience is null or years_experience >= 0),
  education_level text,
  skills text[] not null default '{}',
  desired_salary numeric check (desired_salary is null or desired_salary >= 0),
  desired_salary_currency text,
  remote_preference text not null default 'neutral' check (remote_preference in ('required', 'preferred', 'neutral')),
  relocation_willingness text not null default 'maybe' check (relocation_willingness in ('yes', 'maybe', 'no')),
  career_goals text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.saved_career_markets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  career_slug text not null,
  country_slug text not null,
  favorite boolean not null default false,
  alerts_enabled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, career_slug, country_slug)
);

create table public.saved_career_comparisons (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 120),
  targets jsonb not null check (jsonb_typeof(targets) = 'array'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.career_alert_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  career_slug text not null,
  country_slug text not null,
  alert_types text[] not null default array['salary_updated','new_verified_data'],
  active boolean not null default true,
  last_notified_at timestamptz,
  created_at timestamptz not null default now(),
  unique (user_id, career_slug, country_slug)
);

create table public.career_opportunity_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'draft' check (status in ('draft', 'ready', 'archived')),
  input_snapshot jsonb not null,
  output_snapshot jsonb,
  methodology_version text not null default 'opportunity-ranking-v1',
  evidence_researched_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_entitlements (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan_key text not null default 'free',
  feature_overrides jsonb not null default '{}'::jsonb,
  valid_until timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.user_career_profiles enable row level security;
alter table public.saved_career_markets enable row level security;
alter table public.saved_career_comparisons enable row level security;
alter table public.career_alert_subscriptions enable row level security;
alter table public.career_opportunity_reports enable row level security;
alter table public.user_entitlements enable row level security;

create policy "Users manage their career profile" on public.user_career_profiles for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Users manage their saved career markets" on public.saved_career_markets for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Users manage their saved comparisons" on public.saved_career_comparisons for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Users manage their career alerts" on public.career_alert_subscriptions for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Users read and create their opportunity reports" on public.career_opportunity_reports for select to authenticated using (user_id = auth.uid());
create policy "Users create their opportunity reports" on public.career_opportunity_reports for insert to authenticated with check (user_id = auth.uid());
create policy "Users read their entitlements" on public.user_entitlements for select to authenticated using (user_id = auth.uid());

revoke all privileges on table public.user_career_profiles, public.saved_career_markets, public.saved_career_comparisons, public.career_alert_subscriptions, public.career_opportunity_reports, public.user_entitlements from public, anon;
grant select, insert, update, delete on table public.user_career_profiles, public.saved_career_markets, public.saved_career_comparisons, public.career_alert_subscriptions to authenticated;
grant select, insert on table public.career_opportunity_reports to authenticated;
grant select on table public.user_entitlements to authenticated;
grant usage, select on sequence public.saved_career_markets_id_seq, public.saved_career_comparisons_id_seq, public.career_alert_subscriptions_id_seq, public.career_opportunity_reports_id_seq to authenticated;

create index saved_career_markets_user_idx on public.saved_career_markets (user_id, updated_at desc);
create index saved_career_comparisons_user_idx on public.saved_career_comparisons (user_id, updated_at desc);
create index career_alert_subscriptions_active_idx on public.career_alert_subscriptions (active, career_slug, country_slug);
create index career_opportunity_reports_user_idx on public.career_opportunity_reports (user_id, created_at desc);
