create table if not exists public.career_research_runs (
  id bigint generated by default as identity primary key,
  career_slug text not null,
  country_slug text not null,
  status text not null default 'pending_review'
    check (status in ('pending_review', 'reviewed', 'rejected', 'published', 'failed')),
  schema_version text not null,
  candidate_profile jsonb not null,
  live_profile_snapshot jsonb not null,
  source_name text,
  source_url text,
  researched_at timestamptz not null,
  created_by uuid references auth.users(id) on delete set null,
  reviewed_by uuid references auth.users(id) on delete set null,
  review_notes text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists career_research_runs_target_created_idx
  on public.career_research_runs (career_slug, country_slug, created_at desc);

alter table public.career_research_runs enable row level security;

create policy "Admins can read career research runs"
  on public.career_research_runs for select to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Admins can create career research runs"
  on public.career_research_runs for insert to authenticated
  with check (
    (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
    and created_by = auth.uid()
    and status = 'pending_review'
  );

create policy "Admins can review career research runs"
  on public.career_research_runs for update to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

comment on table public.career_research_runs is
  'Review queue and audit history for normalized Career × Country research candidates. Rows never replace live profiles automatically.';
