alter table public.user_career_profiles
  add column languages text[] not null default '{}',
  add column education_field text,
  add column citizenship_region text,
  add column work_authorization_status text not null default 'unknown'
    check (work_authorization_status in ('authorized', 'requires-permit', 'unknown')),
  add constraint user_career_profiles_languages_count_check check (cardinality(languages) <= 20);

alter table public.career_alert_subscriptions
  drop constraint career_alert_subscriptions_types_check,
  add constraint career_alert_subscriptions_types_check check (
    cardinality(alert_types) between 1 and 8
    and alert_types <@ array['salary_updated','new_verified_data','hiring_outlook_updated','source_freshness_changed','career_score_changed','opportunity_score_changed','new_high_match_jobs','relocation_rule_changed']::text[]
  );

create table public.country_language_evidence (
  id bigint generated by default as identity primary key,
  country_slug text not null,
  career_slug text,
  primary_workplace_language text not null,
  useful_languages text[] not null default '{}',
  english_only_realistic boolean,
  local_language_importance text check (local_language_importance in ('high', 'medium', 'low')),
  recommended_proficiency text,
  requirement_level text not null check (requirement_level in ('legal', 'mandatory', 'preferred', 'market-expectation', 'recommendation')),
  source_name text not null,
  source_url text not null,
  source_authority text not null,
  effective_from date,
  reference_period text,
  retrieved_at timestamptz not null,
  confidence text not null check (confidence in ('high', 'medium', 'low')),
  review_status text not null default 'draft' check (review_status in ('draft', 'review', 'published', 'retired')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.work_authorization_evidence (
  id bigint generated by default as identity primary key,
  origin_region text not null,
  destination_country_slug text not null,
  permit_requirement text not null check (permit_requirement in ('required', 'not-required', 'conditional', 'unknown')),
  employer_sponsorship text not null check (employer_sponsorship in ('required', 'relevant', 'not-generally-required', 'unknown')),
  job_offer_required boolean,
  salary_threshold numeric check (salary_threshold is null or salary_threshold >= 0),
  salary_currency text check (salary_currency is null or salary_currency ~ '^[A-Z]{3}$'),
  salary_period text check (salary_period is null or salary_period in ('annual', 'monthly')),
  qualification_requirement text,
  occupation_restrictions text[] not null default '{}',
  processing_complexity text check (processing_complexity in ('low', 'medium', 'high')),
  source_name text not null,
  source_url text not null,
  source_authority text not null,
  effective_from date,
  retrieved_at timestamptz not null,
  confidence text not null check (confidence in ('high', 'medium', 'low')),
  review_status text not null default 'draft' check (review_status in ('draft', 'review', 'published', 'retired')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_subscriptions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan text not null default 'free' check (plan in ('free', 'pro')),
  subscription_status text not null default 'inactive' check (subscription_status in ('inactive', 'trialing', 'active', 'past_due', 'canceled', 'unpaid', 'incomplete', 'incomplete_expired', 'paused')),
  stripe_customer_id text unique check (stripe_customer_id is null or char_length(stripe_customer_id) between 1 and 255),
  stripe_subscription_id text unique check (stripe_subscription_id is null or char_length(stripe_subscription_id) between 1 and 255),
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  stripe_event_id text not null check (char_length(stripe_event_id) between 1 and 255),
  stripe_event_created bigint not null check (stripe_event_created > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.billing_webhook_events (
  event_id text primary key check (char_length(event_id) between 1 and 255),
  event_type text not null check (char_length(event_type) between 1 and 255),
  event_created bigint not null check (event_created > 0),
  status text not null check (status in ('processing', 'processed', 'failed')),
  processed_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.opportunity_watches (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  career_slug text not null,
  country_slug text not null,
  active boolean not null default true,
  last_evaluated_at timestamptz,
  last_score numeric check (last_score is null or last_score between 0 and 100),
  last_score_version text,
  previous_snapshot jsonb check (previous_snapshot is null or jsonb_typeof(previous_snapshot) = 'object'),
  current_snapshot jsonb check (current_snapshot is null or jsonb_typeof(current_snapshot) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, career_slug, country_slug)
);

alter table public.country_language_evidence enable row level security;
alter table public.work_authorization_evidence enable row level security;
alter table public.user_subscriptions enable row level security;
alter table public.billing_webhook_events enable row level security;
alter table public.opportunity_watches enable row level security;

create policy "Published language evidence is public" on public.country_language_evidence for select using (review_status = 'published');
create policy "Published work authorization evidence is public" on public.work_authorization_evidence for select using (review_status = 'published');
create policy "Users read their subscription" on public.user_subscriptions for select to authenticated using (user_id = auth.uid());
create policy "Users read their opportunity watches" on public.opportunity_watches for select to authenticated using (user_id = auth.uid());

revoke all privileges on table public.country_language_evidence, public.work_authorization_evidence, public.user_subscriptions, public.billing_webhook_events, public.opportunity_watches from public, anon, authenticated;
grant select on table public.country_language_evidence, public.work_authorization_evidence to anon, authenticated;
grant select on table public.user_subscriptions, public.opportunity_watches to authenticated;
grant select, insert, update on table public.user_subscriptions, public.billing_webhook_events, public.user_entitlements to service_role;
grant select, insert, update, delete on table public.opportunity_watches to service_role;
grant usage, select on sequence public.opportunity_watches_id_seq to service_role;

create index country_language_evidence_public_idx on public.country_language_evidence (country_slug, career_slug, review_status);
create index work_authorization_evidence_public_idx on public.work_authorization_evidence (destination_country_slug, origin_region, review_status);
create index opportunity_watches_active_idx on public.opportunity_watches (active, updated_at);

create or replace function public.apply_billing_subscription_event(
  p_user_id uuid,
  p_status text,
  p_stripe_customer_id text,
  p_stripe_subscription_id text,
  p_current_period_end timestamptz,
  p_cancel_at_period_end boolean,
  p_stripe_event_id text,
  p_stripe_event_created bigint
)
returns boolean
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  applied_count integer;
  effective_plan text;
begin
  if p_status not in ('inactive', 'trialing', 'active', 'past_due', 'canceled', 'unpaid', 'incomplete', 'incomplete_expired', 'paused') then
    raise exception 'Unsupported subscription status';
  end if;
  if p_stripe_customer_id is null or p_stripe_subscription_id is null or p_stripe_event_id is null or p_stripe_event_created <= 0 then
    raise exception 'Incomplete Stripe subscription event';
  end if;

  effective_plan := case when p_status in ('active', 'trialing') then 'pro' else 'free' end;
  insert into public.user_subscriptions (
    user_id, plan, subscription_status, stripe_customer_id, stripe_subscription_id,
    current_period_end, cancel_at_period_end, stripe_event_id, stripe_event_created, updated_at
  ) values (
    p_user_id, effective_plan, p_status, p_stripe_customer_id, p_stripe_subscription_id,
    p_current_period_end, p_cancel_at_period_end, p_stripe_event_id, p_stripe_event_created, now()
  )
  on conflict (user_id) do update set
    plan = excluded.plan,
    subscription_status = excluded.subscription_status,
    stripe_customer_id = excluded.stripe_customer_id,
    stripe_subscription_id = excluded.stripe_subscription_id,
    current_period_end = excluded.current_period_end,
    cancel_at_period_end = excluded.cancel_at_period_end,
    stripe_event_id = excluded.stripe_event_id,
    stripe_event_created = excluded.stripe_event_created,
    updated_at = now()
  where excluded.stripe_event_created > public.user_subscriptions.stripe_event_created
     or (excluded.stripe_event_created = public.user_subscriptions.stripe_event_created
         and (excluded.stripe_event_id = public.user_subscriptions.stripe_event_id
              or (excluded.plan = 'free' and public.user_subscriptions.plan = 'pro')));

  get diagnostics applied_count = row_count;
  if applied_count = 0 then
    return false;
  end if;

  insert into public.user_entitlements (user_id, plan_key, valid_until, updated_at)
  values (p_user_id, effective_plan, p_current_period_end, now())
  on conflict (user_id) do update set
    plan_key = excluded.plan_key,
    valid_until = excluded.valid_until,
    updated_at = now();
  return true;
end;
$$;

revoke all on function public.apply_billing_subscription_event(uuid, text, text, text, timestamptz, boolean, text, bigint) from public, anon, authenticated;
grant execute on function public.apply_billing_subscription_event(uuid, text, text, text, timestamptz, boolean, text, bigint) to service_role;
